import { datetime, decimal, index, int, json, mysqlEnum, mysqlTable, text, uniqueIndex, varchar } from "drizzle-orm/mysql-core";

const stamped = {
  createdAt: datetime("created_at").notNull(),
  updatedAt: datetime("updated_at").notNull(),
};

export const companies = mysqlTable("companies", {
  id: varchar("id", { length: 64 }).primaryKey(), name: varchar("name", { length: 200 }).notNull(), phone: varchar("phone", { length: 64 }), website: varchar("website", { length: 255 }), billingEmail: varchar("billing_email", { length: 320 }), reportingEmails: json("reporting_emails").$type<string[]>(), paymentMethod: mysqlEnum("payment_method", ["credit_card", "invoice"]), limsId: varchar("lims_id", { length: 64 }), stripeId: varchar("stripe_id", { length: 64 }), hubspotCompanyId: varchar("hubspot_company_id", { length: 64 }), archivedAt: datetime("archived_at"), ...stamped,
});

export const companyMemberships = mysqlTable("company_memberships", {
  id: varchar("id", { length: 64 }).primaryKey(), userId: int("user_id").notNull(), companyId: varchar("company_id", { length: 64 }).notNull(), role: varchar("role", { length: 80 }).notNull(), viewResults: int("view_results").notNull().default(0), receiveComanCoas: int("receive_coman_coas").notNull().default(0), orderPlacedNotifications: int("order_placed_notifications").notNull().default(0), ...stamped,
}, table => [uniqueIndex("company_membership_user_company_unique").on(table.userId, table.companyId), index("company_membership_company_idx").on(table.companyId)]);

export const skus = mysqlTable("skus", {
  id: varchar("id", { length: 64 }).primaryKey(), name: varchar("name", { length: 200 }).notNull(), code: varchar("code", { length: 120 }).notNull(), supplier: varchar("supplier", { length: 160 }), productId: varchar("product_id", { length: 64 }).notNull(), servingSizeGrams: decimal("serving_size_grams", { precision: 12, scale: 4 }), servingSizeUnit: varchar("serving_size_unit", { length: 32 }), specRequiresServingSize: int("spec_requires_serving_size").notNull().default(0), limsId: varchar("lims_id", { length: 64 }), archivedAt: datetime("archived_at"), ...stamped,
}, table => [index("skus_product_idx").on(table.productId), uniqueIndex("skus_product_code_unique").on(table.productId, table.code)]);

export const shipments = mysqlTable("shipments", {
  id: varchar("id", { length: 64 }).primaryKey(), companyId: varchar("company_id", { length: 64 }).notNull(), status: varchar("status", { length: 80 }).notNull(), carrier: varchar("carrier", { length: 80 }), trackingNumber: varchar("tracking_number", { length: 160 }), estimatedDeliveryDate: datetime("estimated_delivery_date"), preTransitAt: datetime("pre_transit_at"), inTransitAt: datetime("in_transit_at"), outForDeliveryAt: datetime("out_for_delivery_at"), deliveredAt: datetime("delivered_at"), returnToSenderAt: datetime("return_to_sender_at"), failureAt: datetime("failure_at"), errorMessages: json("error_messages").$type<string[]>(), limsId: varchar("lims_id", { length: 64 }), archivedAt: datetime("archived_at"), ...stamped,
}, table => [index("shipments_company_idx").on(table.companyId)]);

export const samples = mysqlTable("samples", {
  id: varchar("id", { length: 64 }).primaryKey(), name: varchar("name", { length: 200 }).notNull(), orderId: varchar("order_id", { length: 64 }).notNull(), skuId: varchar("sku_id", { length: 64 }).notNull(), lot: varchar("lot", { length: 160 }), batch: varchar("batch", { length: 160 }), composite: int("composite").notNull().default(0), numberOfComposites: int("number_of_composites"), parentId: varchar("parent_id", { length: 64 }), shipmentId: varchar("shipment_id", { length: 64 }), laboratoryId: varchar("laboratory_id", { length: 64 }), timeOfCollection: datetime("time_of_collection").notNull(), servingSizeGrams: decimal("serving_size_grams", { precision: 12, scale: 4 }), servingSizeUnit: varchar("serving_size_unit", { length: 32 }), labReportedServingSize: decimal("lab_reported_serving_size", { precision: 12, scale: 4 }), labReportedServingSizeUnit: varchar("lab_reported_serving_size_unit", { length: 32 }), sfpText: text("sfp_text"), limsId: varchar("lims_id", { length: 64 }), archivedAt: datetime("archived_at"), ...stamped,
}, table => [index("samples_sku_collected_idx").on(table.skuId, table.timeOfCollection), index("samples_order_idx").on(table.orderId)]);

export const assays = mysqlTable("assays", {
  id: varchar("id", { length: 64 }).primaryKey(), name: varchar("name", { length: 200 }).notNull(), method: varchar("method", { length: 200 }), methodDescription: text("method_description"), price: decimal("price", { precision: 12, scale: 2 }), laboratoryId: varchar("laboratory_id", { length: 64 }), accredited: int("accredited").notNull().default(0), forProp65: int("for_prop_65").notNull().default(0), forAb899: int("for_ab899").notNull().default(0), purchasable: int("purchasable").notNull().default(1), requiresSfp: int("requires_sfp").notNull().default(0), minimumSampleSizeGrams: decimal("minimum_sample_size_grams", { precision: 12, scale: 4 }), averageTurnaroundTimeHours: int("average_turnaround_time_hours"), turnaroundTimeLabel: varchar("turnaround_time_label", { length: 120 }), weekendStart: int("weekend_start").notNull().default(0), holidayStart: int("holiday_start").notNull().default(0), sameDayCutoffHour: int("same_day_cutoff_hour"), limsId: varchar("lims_id", { length: 64 }), archivedAt: datetime("archived_at"), ...stamped,
});

export const assayCompanyPrices = mysqlTable("assay_company_prices", { id: varchar("id", { length: 64 }).primaryKey(), assayId: varchar("assay_id", { length: 64 }).notNull(), companyId: varchar("company_id", { length: 64 }).notNull(), price: decimal("price", { precision: 12, scale: 2 }).notNull(), ...stamped }, table => [uniqueIndex("assay_company_price_unique").on(table.assayId, table.companyId)]);
export const turnaroundTimes = mysqlTable("turnaround_times", { id: varchar("id", { length: 64 }).primaryKey(), assayId: varchar("assay_id", { length: 64 }).notNull(), days: int("days").notNull(), fee: decimal("fee", { precision: 12, scale: 2 }).notNull(), feeType: varchar("fee_type", { length: 80 }).notNull(), ...stamped }, table => [index("turnaround_times_assay_idx").on(table.assayId)]);
export const analytes = mysqlTable("analytes", { id: varchar("id", { length: 64 }).primaryKey(), name: varchar("name", { length: 160 }).notNull(), shortName: varchar("short_name", { length: 64 }), categoryId: varchar("category_id", { length: 64 }), limsId: varchar("lims_id", { length: 64 }), ...stamped });
export const analyteCompanyUnits = mysqlTable("analyte_company_units", { id: varchar("id", { length: 64 }).primaryKey(), analyteId: varchar("analyte_id", { length: 64 }).notNull(), companyId: varchar("company_id", { length: 64 }).notNull(), platformUnit: varchar("platform_unit", { length: 32 }).notNull(), coaUnit: varchar("coa_unit", { length: 32 }).notNull(), pipUnit: varchar("pip_unit", { length: 32 }).notNull(), ...stamped }, table => [uniqueIndex("analyte_company_units_unique").on(table.analyteId, table.companyId)]);
export const testResults = mysqlTable("test_results", { id: varchar("id", { length: 64 }).primaryKey(), testId: varchar("test_id", { length: 64 }).notNull(), analyteId: varchar("analyte_id", { length: 64 }).notNull(), concentration: decimal("concentration", { precision: 16, scale: 6 }), unit: varchar("unit", { length: 32 }).notNull(), lod: decimal("lod", { precision: 16, scale: 6 }), loq: decimal("loq", { precision: 16, scale: 6 }), evaluation: varchar("evaluation", { length: 120 }), observation: text("observation"), limsId: varchar("lims_id", { length: 64 }), ...stamped }, table => [uniqueIndex("test_results_test_analyte_unique").on(table.testId, table.analyteId), index("test_results_analyte_idx").on(table.analyteId)]);
export const reports = mysqlTable("reports", { id: varchar("id", { length: 64 }).primaryKey(), testId: varchar("test_id", { length: 64 }), state: varchar("state", { length: 80 }).notNull(), attachedTo: varchar("attached_to", { length: 120 }), isPublic: int("is_public").notNull().default(0), dateGenerated: datetime("date_generated"), datePublished: datetime("date_published"), renderStatus: varchar("render_status", { length: 80 }), limsId: varchar("lims_id", { length: 64 }), ...stamped }, table => [index("reports_test_idx").on(table.testId)]);
export const partnerships = mysqlTable("partnerships", { id: varchar("id", { length: 64 }).primaryKey(), sourceCompanyId: varchar("source_company_id", { length: 64 }).notNull(), targetCompanyId: varchar("target_company_id", { length: 64 }).notNull(), role: varchar("role", { length: 80 }).notNull(), payer: varchar("payer", { length: 80 }), active: int("active").notNull().default(1), viewResults: int("view_results").notNull().default(0), ...stamped }, table => [uniqueIndex("partnership_pair_unique").on(table.sourceCompanyId, table.targetCompanyId), index("partnership_target_idx").on(table.targetCompanyId)]);

type LimitBasis = "per_serving" | "per_kg" | "per_capsule" | "per_100g";
const limitColumns = { limitType: varchar("limit_type", { length: 80 }).notNull(), limitUnit: varchar("limit_unit", { length: 32 }), limitBasis: mysqlEnum("limit_basis", ["per_serving", "per_kg", "per_capsule", "per_100g"]).$type<LimitBasis>(), lowerBound: decimal("lower_bound", { precision: 16, scale: 6 }), upperBound: decimal("upper_bound", { precision: 16, scale: 6 }) };
export const testLimits = mysqlTable("test_limits", { id: varchar("id", { length: 64 }).primaryKey(), testId: varchar("test_id", { length: 64 }).notNull(), analyteId: varchar("analyte_id", { length: 64 }).notNull(), customized: int("customized").notNull().default(0), source: varchar("source", { length: 200 }).notNull(), limsId: varchar("lims_id", { length: 64 }), ...limitColumns, ...stamped }, table => [index("test_limits_test_analyte_idx").on(table.testId, table.analyteId)]);
export const limitGroups = mysqlTable("limit_groups", { id: varchar("id", { length: 64 }).primaryKey(), name: varchar("name", { length: 200 }).notNull(), source: varchar("source", { length: 200 }).notNull(), limsId: varchar("lims_id", { length: 64 }), ...stamped });
export const limitGroupSkuAssignments = mysqlTable("limit_group_sku_assignments", { id: varchar("id", { length: 64 }).primaryKey(), limitGroupId: varchar("limit_group_id", { length: 64 }).notNull(), skuId: varchar("sku_id", { length: 64 }).notNull(), missingServingSize: int("missing_serving_size").notNull().default(0), ...stamped }, table => [uniqueIndex("limit_group_sku_unique").on(table.limitGroupId, table.skuId)]);
export const actionLimits = mysqlTable("action_limits", { id: varchar("id", { length: 64 }).primaryKey(), skuId: varchar("sku_id", { length: 64 }).notNull(), analyteId: varchar("analyte_id", { length: 64 }).notNull(), ...limitColumns, ...stamped }, table => [index("action_limits_sku_analyte_idx").on(table.skuId, table.analyteId)]);
export const regulatoryLimits = mysqlTable("regulatory_limits", { id: varchar("id", { length: 64 }).primaryKey(), name: varchar("name", { length: 200 }).notNull(), analyteId: varchar("analyte_id", { length: 64 }).notNull(), citation: varchar("citation", { length: 255 }), ...limitColumns, ...stamped }, table => [index("regulatory_limits_regime_analyte_idx").on(table.name, table.analyteId)]);
export const specifications = mysqlTable("specifications", { id: varchar("id", { length: 64 }).primaryKey(), skuId: varchar("sku_id", { length: 64 }).notNull(), analyteId: varchar("analyte_id", { length: 64 }).notNull(), source: varchar("source", { length: 200 }).notNull(), ...limitColumns, ...stamped }, table => [uniqueIndex("specifications_sku_analyte_unique").on(table.skuId, table.analyteId)]);
export const stabilityStudies = mysqlTable("stability_studies", { id: varchar("id", { length: 64 }).primaryKey(), name: varchar("name", { length: 200 }).notNull(), companyId: varchar("company_id", { length: 64 }).notNull(), skuId: varchar("sku_id", { length: 64 }).notNull(), arm: varchar("arm", { length: 100 }), requiredUnits: int("required_units"), ...stamped }, table => [index("stability_studies_sku_idx").on(table.skuId)]);
export const stabilityStudyTimePoints = mysqlTable("stability_study_time_points", { id: varchar("id", { length: 64 }).primaryKey(), stabilityStudyId: varchar("stability_study_id", { length: 64 }).notNull(), monthOffset: int("month_offset").notNull(), date: datetime("date").notNull(), ...stamped }, table => [index("stability_points_study_idx").on(table.stabilityStudyId)]);
