import { datetime, decimal, index, int, json, mediumtext, mysqlEnum, mysqlTable, text, timestamp, uniqueIndex, varchar } from "drizzle-orm/mysql-core";

export const users = mysqlTable("users", {
  id: int("id").autoincrement().primaryKey(),
  openId: varchar("openId", { length: 64 }).notNull().unique(),
  name: text("name"), email: varchar("email", { length: 320 }), loginMethod: varchar("loginMethod", { length: 64 }),
  role: mysqlEnum("role", ["user", "admin"]).default("user").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(), updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(), lastSignedIn: timestamp("lastSignedIn").defaultNow().notNull(),
});

export const teamMembers = mysqlTable("team_members", {
  id: varchar("id", { length: 64 }).primaryKey(), name: varchar("name", { length: 160 }).notNull(), email: varchar("email", { length: 255 }).notNull(), role: mysqlEnum("role", ["ae", "lab_director", "admin"]).notNull(),
});
export const accounts = mysqlTable("accounts", {
  id: varchar("id", { length: 64 }).primaryKey(), name: varchar("name", { length: 200 }).notNull(), accountType: mysqlEnum("account_type", ["brand", "coman"]).notNull(), annualSpend: int("annual_spend").notNull(), slackChannel: varchar("slack_channel", { length: 100 }), ownerId: varchar("owner_id", { length: 64 }).notNull(),
});
export const contacts = mysqlTable("contacts", {
  id: varchar("id", { length: 64 }).primaryKey(), accountId: varchar("account_id", { length: 64 }).notNull(), name: varchar("name", { length: 160 }).notNull(), email: varchar("email", { length: 255 }), slackUserId: varchar("slack_user_id", { length: 100 }), slackWorkspaceId: varchar("slack_workspace_id", { length: 64 }), hubspotPortalId: varchar("hubspot_portal_id", { length: 64 }), hubspotContactId: varchar("hubspot_contact_id", { length: 64 }), identityStatus: mysqlEnum("identity_status", ["pending", "verified", "revoked"]).notNull().default("pending"), verifiedAt: datetime("verified_at"), roleTitle: varchar("role_title", { length: 160 }), hasPlatformLogin: int("has_platform_login").notNull().default(0),
}, table => [index("contacts_account_idx").on(table.accountId), uniqueIndex("contacts_slack_identity_unique").on(table.slackWorkspaceId, table.slackUserId), uniqueIndex("contacts_hubspot_identity_unique").on(table.hubspotPortalId, table.hubspotContactId)]);
export const products = mysqlTable("products", { id: varchar("id", { length: 64 }).primaryKey(), accountId: varchar("account_id", { length: 64 }).notNull(), name: varchar("name", { length: 200 }).notNull(), category: varchar("category", { length: 100 }).notNull(), servingSizeG: decimal("serving_size_g", { precision: 10, scale: 2 }) });
export const lots = mysqlTable("lots", { id: varchar("id", { length: 64 }).primaryKey(), productId: varchar("product_id", { length: 64 }).notNull(), comanId: varchar("coman_id", { length: 64 }), producedAt: datetime("produced_at").notNull() });
export const orders = mysqlTable("orders", { id: varchar("id", { length: 64 }).primaryKey(), accountId: varchar("account_id", { length: 64 }).notNull(), placedAt: datetime("placed_at").notNull(), promisedAt: datetime("promised_at"), status: varchar("status", { length: 64 }).notNull(), queuePosition: int("queue_position"), assayGroup: varchar("assay_group", { length: 100 }) });
export const tests = mysqlTable("tests", { id: varchar("id", { length: 64 }).primaryKey(), orderId: varchar("order_id", { length: 64 }), lotId: varchar("lot_id", { length: 64 }), assay: varchar("assay", { length: 100 }).notNull(), status: varchar("status", { length: 64 }).notNull(), completedAt: datetime("completed_at") });
export const results = mysqlTable("results", { id: varchar("id", { length: 64 }).primaryKey(), testId: varchar("test_id", { length: 64 }).notNull(), analyte: varchar("analyte", { length: 100 }).notNull(), value: decimal("value", { precision: 14, scale: 4 }), unit: varchar("unit", { length: 64 }).notNull(), isNonDetect: int("is_non_detect").notNull().default(0), loq: decimal("loq", { precision: 14, scale: 4 }), reportedAt: datetime("reported_at").notNull() });
export const specs = mysqlTable("specs", { id: varchar("id", { length: 64 }).primaryKey(), scope: varchar("scope", { length: 64 }).notNull(), scopeId: varchar("scope_id", { length: 64 }), category: varchar("category", { length: 100 }), analyte: varchar("analyte", { length: 100 }).notNull(), limitValue: decimal("limit_value", { precision: 14, scale: 4 }), limitUnit: varchar("limit_unit", { length: 64 }), source: varchar("source", { length: 100 }).notNull(), citation: text("citation"), isPlaceholder: int("is_placeholder").notNull().default(0) });
export const kbEntries = mysqlTable("kb_entries", { id: varchar("id", { length: 64 }).primaryKey(), questionPattern: varchar("question_pattern", { length: 255 }).notNull(), answer: text("answer").notNull(), author: varchar("author", { length: 160 }).notNull(), approvedBy: varchar("approved_by", { length: 160 }), createdAt: datetime("created_at").notNull() });
export const interactions = mysqlTable("interactions", {
  id: varchar("id", { length: 80 }).primaryKey(), source: varchar("source", { length: 32 }).notNull(), channelRef: varchar("channel_ref", { length: 180 }), contactId: varchar("contact_id", { length: 64 }), accountId: varchar("account_id", { length: 64 }), ownerId: varchar("owner_id", { length: 64 }), receivedAt: datetime("received_at").notNull(), rawText: text("raw_text").notNull(), intents: json("intents").$type<string[]>(), confidence: decimal("confidence", { precision: 5, scale: 4 }), imminentAction: int("imminent_action").notNull().default(0), classifierMethod: varchar("classifier_method", { length: 40 }).notNull(), baseLane: mysqlEnum("base_lane", ["auto", "assisted", "escalate"]), lane: mysqlEnum("lane", ["auto", "assisted", "escalate"]).notNull(), laneReasons: json("lane_reasons").$type<string[]>().notNull(), verifiedReplyStatus: mysqlEnum("verified_reply_status", ["eligible", "ineligible"]).notNull().default("ineligible"), replyGateReasons: json("reply_gate_reasons").$type<string[]>().notNull(), acknowledgment: text("acknowledgment").notNull(), draft: text("draft"), evidence: json("evidence").$type<Array<{ label: string; value: string; source: string; citable: boolean }>>().notNull(), precedent: json("precedent").$type<{ answer: string; author: string; approvedBy?: string | null }>(), sendAllowed: int("send_allowed").notNull().default(0), sendDisabled: int("send_disabled").notNull().default(0), status: mysqlEnum("status", ["open", "awaiting_customer", "auto_resolved", "resolved"]).notNull().default("open"), msToAck: int("ms_to_ack").notNull(), humanMinutesSaved: decimal("human_minutes_saved", { precision: 8, scale: 2 }).notNull().default("0"), queuePriority: int("queue_priority").notNull(), slaMinutes: int("sla_minutes").notNull(), resolvedAt: datetime("resolved_at"), resolvedBy: varchar("resolved_by", { length: 64 }),
}, table => [uniqueIndex("interaction_dedup_unique").on(table.source, table.channelRef), index("interaction_owner_idx").on(table.ownerId, table.lane, table.receivedAt), index("interaction_account_idx").on(table.accountId)]);
export const responseFeedback = mysqlTable("response_feedback", { id: varchar("id", { length: 80 }).primaryKey(), interactionId: varchar("interaction_id", { length: 80 }).notNull(), userId: varchar("user_id", { length: 64 }).notNull(), draftedText: text("drafted_text"), sentText: text("sent_text").notNull(), editRatio: decimal("edit_ratio", { precision: 6, scale: 4 }).notNull(), category: varchar("category", { length: 100 }).notNull(), lane: varchar("lane", { length: 32 }).notNull(), overrideReason: text("override_reason"), createdAt: datetime("created_at").notNull() });
export const clarifications = mysqlTable("clarifications", { id: varchar("id", { length: 80 }).primaryKey(), interactionId: varchar("interaction_id", { length: 80 }).notNull(), question: text("question").notNull(), askedAt: datetime("asked_at").notNull(), answeredAt: datetime("answered_at") });
export const knowledgeSources = mysqlTable("knowledge_sources", {
  id: varchar("id", { length: 96 }).primaryKey(), canonicalUrl: varchar("canonical_url", { length: 500 }).notNull().unique(), title: varchar("title", { length: 300 }).notNull(), sourceType: mysqlEnum("source_type", ["insight", "test_menu", "compliance"]).notNull(), retrievalStatus: mysqlEnum("retrieval_status", ["eligible", "discovery_only", "disabled"]).notNull().default("eligible"), answerSafety: mysqlEnum("answer_safety", ["general_knowledge", "review_required"]).notNull().default("general_knowledge"), discoveryScore: decimal("discovery_score", { precision: 5, scale: 4 }), lastFetchedAt: datetime("last_fetched_at"), createdAt: datetime("created_at").notNull(), updatedAt: datetime("updated_at").notNull(),
}, table => [index("knowledge_sources_status_idx").on(table.retrievalStatus, table.answerSafety)]);
export const knowledgeDocuments = mysqlTable("knowledge_documents", {
  id: varchar("id", { length: 96 }).primaryKey(), sourceId: varchar("source_id", { length: 96 }).notNull(), content: mediumtext("content").notNull(), contentHash: varchar("content_hash", { length: 64 }).notNull(), fetchedAt: datetime("fetched_at").notNull(), indexedAt: datetime("indexed_at").notNull(), status: mysqlEnum("status", ["indexed", "failed", "superseded"]).notNull().default("indexed"),
}, table => [index("knowledge_documents_source_idx").on(table.sourceId, table.status), uniqueIndex("knowledge_document_hash_unique").on(table.sourceId, table.contentHash)]);
export const knowledgeRetrievalEvents = mysqlTable("knowledge_retrieval_events", {
  id: varchar("id", { length: 96 }).primaryKey(), queryText: text("query_text").notNull(), interactionId: varchar("interaction_id", { length: 80 }), retrievedAt: datetime("retrieved_at").notNull(), topScore: decimal("top_score", { precision: 5, scale: 4 }).notNull().default("0"), sourceCount: int("source_count").notNull().default(0), gate: mysqlEnum("gate", ["open", "closed"]).notNull(), reasons: json("reasons").$type<string[]>().notNull(),
}, table => [index("knowledge_retrieval_events_interaction_idx").on(table.interactionId, table.retrievedAt)]);
export const hubspotOauthSessions = mysqlTable("hubspot_oauth_sessions", {
  id: varchar("id", { length: 96 }).primaryKey(), stateHash: varchar("state_hash", { length: 64 }).notNull().unique(), codeVerifierEncrypted: text("code_verifier_encrypted").notNull(), requestedByUserId: varchar("requested_by_user_id", { length: 64 }).notNull(), createdAt: datetime("created_at").notNull(), expiresAt: datetime("expires_at").notNull(), usedAt: datetime("used_at"),
}, table => [index("hubspot_oauth_sessions_expiry_idx").on(table.expiresAt)]);
export const hubspotConnections = mysqlTable("hubspot_connections", {
  id: varchar("id", { length: 96 }).primaryKey(), connectedByUserId: varchar("connected_by_user_id", { length: 64 }).notNull(), portalId: varchar("portal_id", { length: 64 }), accessTokenEncrypted: text("access_token_encrypted").notNull(), refreshTokenEncrypted: text("refresh_token_encrypted").notNull(), accessTokenExpiresAt: datetime("access_token_expires_at"), status: mysqlEnum("status", ["active", "revoked", "error"]).notNull().default("active"), connectedAt: datetime("connected_at").notNull(), updatedAt: datetime("updated_at").notNull(),
}, table => [index("hubspot_connections_status_idx").on(table.status, table.updatedAt)]);

export type User = typeof users.$inferSelect;
export type InsertUser = typeof users.$inferInsert;
