import { datetime, decimal, index, int, json, mediumtext, mysqlEnum, mysqlTable, text, timestamp, uniqueIndex, varchar } from "drizzle-orm/mysql-core";

export const users = mysqlTable("users", {
  id: int("id").autoincrement().primaryKey(),
  openId: varchar("openId", { length: 64 }).unique(),
  name: text("name"), email: varchar("email", { length: 320 }), loginMethod: mysqlEnum("loginMethod", ["google", "slack"]).notNull().default("slack"),
  firstName: varchar("first_name", { length: 120 }), lastName: varchar("last_name", { length: 120 }), staffuser: int("staffuser").notNull().default(0), confirmedAt: datetime("confirmed_at"),
  slackWorkspaceId: varchar("slack_workspace_id", { length: 64 }), slackUserId: varchar("slack_user_id", { length: 100 }), hubspotPortalId: varchar("hubspot_portal_id", { length: 64 }), hubspotContactId: varchar("hubspot_contact_id", { length: 64 }), testingPlatformUserId: varchar("testing_platform_user_id", { length: 64 }), limsId: varchar("lims_id", { length: 64 }),
  role: mysqlEnum("role", ["user", "admin"]).default("user").notNull(), identityStatus: mysqlEnum("identity_status", ["pending", "verified", "revoked"]).notNull().default("pending"), verifiedAt: datetime("verified_at"),
  createdAt: timestamp("createdAt").defaultNow().notNull(), updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(), lastSignedIn: timestamp("lastSignedIn").defaultNow().notNull(),
}, table => [uniqueIndex("users_slack_identity_unique").on(table.slackWorkspaceId, table.slackUserId), uniqueIndex("users_hubspot_identity_unique").on(table.hubspotPortalId, table.hubspotContactId), uniqueIndex("users_testing_platform_identity_unique").on(table.testingPlatformUserId)]);

export const teamMembers = mysqlTable("team_members", {
  id: varchar("id", { length: 64 }).primaryKey(), userId: int("user_id"), name: varchar("name", { length: 160 }).notNull(), email: varchar("email", { length: 255 }).notNull(), role: mysqlEnum("role", ["ae", "lab_director", "admin"]).notNull(), slackUserId: varchar("slack_user_id", { length: 100 }), slackWorkspaceId: varchar("slack_workspace_id", { length: 64 }),
}, table => [uniqueIndex("team_members_slack_identity_unique").on(table.slackWorkspaceId, table.slackUserId)]);
export const slackMcpIdentityRequests = mysqlTable("slack_mcp_identity_requests", {
  id: varchar("id", { length: 96 }).primaryKey(), slackWorkspaceId: varchar("slack_workspace_id", { length: 64 }).notNull(), slackUserId: varchar("slack_user_id", { length: 100 }).notNull(), enterpriseId: varchar("enterprise_id", { length: 64 }), status: mysqlEnum("status", ["pending", "approved", "rejected"]).notNull().default("pending"), firstSeenAt: datetime("first_seen_at").notNull(), lastSeenAt: datetime("last_seen_at").notNull(), approvedTeamMemberId: varchar("approved_team_member_id", { length: 64 }), approvedAt: datetime("approved_at"),
}, table => [uniqueIndex("slack_mcp_identity_request_unique").on(table.slackWorkspaceId, table.slackUserId), index("slack_mcp_identity_request_status_idx").on(table.status, table.lastSeenAt)]);
export const externalSlackIdentityCandidates = mysqlTable("external_slack_identity_candidates", {
  id: varchar("id", { length: 96 }).primaryKey(), slackWorkspaceId: varchar("slack_workspace_id", { length: 64 }).notNull(), slackUserId: varchar("slack_user_id", { length: 100 }).notNull(), status: mysqlEnum("status", ["pending", "mapped", "ignored"]).notNull().default("pending"), firstSeenAt: datetime("first_seen_at").notNull(), lastSeenAt: datetime("last_seen_at").notNull(), lastChannelId: varchar("last_channel_id", { length: 100 }), lastChannelType: varchar("last_channel_type", { length: 24 }), externallySharedChannel: int("externally_shared_channel").notNull().default(0), sourceTransport: mysqlEnum("source_transport", ["custom_bridge", "native_slack"]).notNull(), lastInteractionId: varchar("last_interaction_id", { length: 80 }), resolvedContactId: varchar("resolved_contact_id", { length: 64 }), resolvedAt: datetime("resolved_at"), resolvedByUserId: varchar("resolved_by_user_id", { length: 64 }),
}, table => [uniqueIndex("external_slack_identity_candidate_unique").on(table.slackWorkspaceId, table.slackUserId), index("external_slack_identity_candidate_status_idx").on(table.status, table.lastSeenAt)]);
export const integrationAuditEvents = mysqlTable("integration_audit_events", {
  id: varchar("id", { length: 96 }).primaryKey(), surface: mysqlEnum("surface", ["slack_ingest", "mcp", "bobby"]).notNull(), eventType: varchar("event_type", { length: 80 }).notNull(), outcome: mysqlEnum("outcome", ["accepted", "rejected", "error"]).notNull(), statusCode: int("status_code").notNull(), slackWorkspaceId: varchar("slack_workspace_id", { length: 64 }), slackUserId: varchar("slack_user_id", { length: 100 }), method: varchar("method", { length: 100 }), toolName: varchar("tool_name", { length: 120 }), interactionId: varchar("interaction_id", { length: 80 }), metadata: json("metadata").$type<Record<string, unknown>>().notNull(), createdAt: datetime("created_at").notNull(),
}, table => [index("integration_audit_surface_created_idx").on(table.surface, table.createdAt), index("integration_audit_outcome_created_idx").on(table.outcome, table.createdAt)]);
export const ingestChannelPolicies = mysqlTable("ingest_channel_policies", {
  id: varchar("id", { length: 96 }).primaryKey(), slackWorkspaceId: varchar("slack_workspace_id", { length: 64 }).notNull(), channelId: varchar("channel_id", { length: 100 }).notNull(), authoritativeTransport: mysqlEnum("authoritative_transport", ["native_slack", "custom_bridge", "disabled"]).notNull(), enabled: int("enabled").notNull().default(1), createdAt: datetime("created_at").notNull(), updatedAt: datetime("updated_at").notNull(),
}, table => [uniqueIndex("ingest_channel_policy_unique").on(table.slackWorkspaceId, table.channelId), index("ingest_channel_policy_transport_idx").on(table.authoritativeTransport, table.enabled)]);
export const bobbySupportRequests = mysqlTable("bobby_support_requests", {
  requestId: varchar("request_id", { length: 128 }).primaryKey(), schemaVersion: varchar("schema_version", { length: 32 }).notNull(), slackWorkspaceId: varchar("slack_workspace_id", { length: 64 }).notNull(), slackUserId: varchar("slack_user_id", { length: 100 }).notNull(), interactionId: varchar("interaction_id", { length: 80 }), status: mysqlEnum("status", ["answered", "needs_more_info", "escalate", "no_match"]).notNull(), response: json("response").$type<Record<string, unknown>>().notNull(), createdAt: datetime("created_at").notNull(), updatedAt: datetime("updated_at").notNull(),
}, table => [index("bobby_support_requests_slack_identity_idx").on(table.slackWorkspaceId, table.slackUserId, table.createdAt), index("bobby_support_requests_interaction_idx").on(table.interactionId)]);
export const accounts = mysqlTable("accounts", {
  id: varchar("id", { length: 64 }).primaryKey(), name: varchar("name", { length: 200 }).notNull(), accountType: mysqlEnum("account_type", ["brand", "coman"]).notNull(), annualSpend: int("annual_spend").notNull(), slackChannel: varchar("slack_channel", { length: 100 }), ownerId: varchar("owner_id", { length: 64 }).notNull(), ownerUserId: int("owner_user_id"), hubspotPortalId: varchar("hubspot_portal_id", { length: 64 }), hubspotCompanyId: varchar("hubspot_company_id", { length: 64 }), testingPlatformAccountId: varchar("testing_platform_account_id", { length: 64 }),
}, table => [uniqueIndex("accounts_hubspot_company_unique").on(table.hubspotPortalId, table.hubspotCompanyId), uniqueIndex("accounts_testing_platform_unique").on(table.testingPlatformAccountId)]);
export const supportOwners = mysqlTable("support_owners", {
  id: varchar("id", { length: 64 }).primaryKey(), name: varchar("name", { length: 160 }).notNull(), email: varchar("email", { length: 320 }).notNull(), role: mysqlEnum("role", ["ae", "am"]).notNull(), active: int("active").notNull().default(1), createdAt: datetime("created_at").notNull(), updatedAt: datetime("updated_at").notNull(),
}, table => [uniqueIndex("support_owners_email_unique").on(table.email), index("support_owners_active_idx").on(table.active, table.name)]);
export const accountRelationships = mysqlTable("account_relationships", {
  id: varchar("id", { length: 96 }).primaryKey(), comanAccountId: varchar("coman_account_id", { length: 64 }).notNull(), brandAccountId: varchar("brand_account_id", { length: 64 }).notNull(), relationshipType: mysqlEnum("relationship_type", ["coman_brand"]).notNull().default("coman_brand"), active: int("active").notNull().default(1), createdAt: datetime("created_at").notNull(), updatedAt: datetime("updated_at").notNull(),
}, table => [uniqueIndex("account_relationship_pair_unique").on(table.comanAccountId, table.brandAccountId), index("account_relationship_coman_idx").on(table.comanAccountId, table.active), index("account_relationship_brand_idx").on(table.brandAccountId, table.active)]);
export const contacts = mysqlTable("contacts", {
  id: varchar("id", { length: 64 }).primaryKey(), userId: int("user_id"), accountId: varchar("account_id", { length: 64 }).notNull(), internalOwnerUserId: int("internal_owner_user_id"), name: varchar("name", { length: 160 }).notNull(), email: varchar("email", { length: 255 }), slackUserId: varchar("slack_user_id", { length: 100 }), slackWorkspaceId: varchar("slack_workspace_id", { length: 64 }), hubspotPortalId: varchar("hubspot_portal_id", { length: 64 }), hubspotContactId: varchar("hubspot_contact_id", { length: 64 }), identityStatus: mysqlEnum("identity_status", ["pending", "verified", "revoked"]).notNull().default("pending"), verifiedAt: datetime("verified_at"), roleTitle: varchar("role_title", { length: 160 }), hasPlatformLogin: int("has_platform_login").notNull().default(0),
}, table => [index("contacts_account_idx").on(table.accountId), index("contacts_user_idx").on(table.userId), index("contacts_internal_owner_idx").on(table.internalOwnerUserId), uniqueIndex("contacts_slack_identity_unique").on(table.slackWorkspaceId, table.slackUserId), uniqueIndex("contacts_hubspot_identity_unique").on(table.hubspotPortalId, table.hubspotContactId)]);
export const accountMemberships = mysqlTable("account_memberships", {
  id: varchar("id", { length: 96 }).primaryKey(), accountId: varchar("account_id", { length: 64 }).notNull(), userId: int("user_id").notNull(), membershipType: mysqlEnum("membership_type", ["buyer", "coman"]).notNull(), status: mysqlEnum("status", ["pending", "active", "inactive", "revoked"]).notNull().default("pending"), buyerUserId: int("buyer_user_id"), internalOwnerUserId: int("internal_owner_user_id").notNull(), receiveComanCoas: int("receive_coman_coas").notNull().default(0), createdAt: datetime("created_at").notNull(), updatedAt: datetime("updated_at").notNull(),
}, table => [uniqueIndex("account_membership_user_account_unique").on(table.userId, table.accountId), uniqueIndex("account_membership_active_buyer_unique").on(table.buyerUserId), index("account_membership_account_idx").on(table.accountId, table.status), index("account_membership_owner_idx").on(table.internalOwnerUserId, table.status)]);
export const comanContactBrandAccess = mysqlTable("coman_contact_brand_access", {
  id: varchar("id", { length: 96 }).primaryKey(), contactId: varchar("contact_id", { length: 64 }).notNull(), comanAccountId: varchar("coman_account_id", { length: 64 }).notNull(), brandAccountId: varchar("brand_account_id", { length: 64 }).notNull(), canView: int("can_view").notNull().default(1), canEdit: int("can_edit").notNull().default(0), approvalScope: mysqlEnum("approval_scope", ["none", "view", "edit"]).notNull().default("view"), active: int("active").notNull().default(1), createdAt: datetime("created_at").notNull(), updatedAt: datetime("updated_at").notNull(),
}, table => [uniqueIndex("coman_contact_brand_access_unique").on(table.contactId, table.brandAccountId), index("coman_contact_brand_access_coman_idx").on(table.comanAccountId, table.active), index("coman_contact_brand_access_brand_idx").on(table.brandAccountId, table.active)]);
export const contactIdentities = mysqlTable("contact_identities", {
  id: varchar("id", { length: 96 }).primaryKey(), contactId: varchar("contact_id", { length: 64 }).notNull(), userId: int("user_id"), provider: mysqlEnum("provider", ["slack", "hubspot", "email"]).notNull(), tenantId: varchar("tenant_id", { length: 100 }).notNull(), externalId: varchar("external_id", { length: 255 }).notNull(), emailNormalized: varchar("email_normalized", { length: 320 }), verificationStatus: mysqlEnum("verification_status", ["pending", "verified", "revoked", "expired"]).notNull().default("pending"), verificationMethod: mysqlEnum("verification_method", ["admin_confirmed", "hubspot_exact_email", "provisioned", "customer_claimed"]).notNull(), verifiedAt: datetime("verified_at"), revokedAt: datetime("revoked_at"), verifiedByUserId: varchar("verified_by_user_id", { length: 64 }), attributes: json("attributes").$type<Record<string, unknown>>(), createdAt: datetime("created_at").notNull(), updatedAt: datetime("updated_at").notNull(),
}, table => [uniqueIndex("contact_identity_provider_tenant_external_unique").on(table.provider, table.tenantId, table.externalId), index("contact_identity_contact_status_idx").on(table.contactId, table.verificationStatus), index("contact_identity_user_status_idx").on(table.userId, table.verificationStatus)]);
export const products = mysqlTable("products", { id: varchar("id", { length: 64 }).primaryKey(), accountId: varchar("account_id", { length: 64 }).notNull(), appAccountId: varchar("app_account_id", { length: 64 }), name: varchar("name", { length: 200 }).notNull(), category: varchar("category", { length: 100 }).notNull(), servingSizeG: decimal("serving_size_g", { precision: 10, scale: 2 }), companyId: varchar("company_id", { length: 64 }), testingPlatformCompanyId: varchar("testing_platform_company_id", { length: 64 }), brand: varchar("brand", { length: 160 }), productType: mysqlEnum("product_type", ["finished_good", "raw_material", "research_and_development", "industry_benchmarking"]), shelfLife: varchar("shelf_life", { length: 120 }), testingPlatformProductId: varchar("testing_platform_product_id", { length: 64 }), limsId: varchar("lims_id", { length: 64 }), createdAt: datetime("created_at"), updatedAt: datetime("updated_at"), archivedAt: datetime("archived_at") }, table => [index("products_company_idx").on(table.companyId), index("products_app_account_idx").on(table.appAccountId), index("products_testing_platform_company_idx").on(table.testingPlatformCompanyId), uniqueIndex("products_testing_platform_unique").on(table.testingPlatformProductId)]);
export const lots = mysqlTable("lots", { id: varchar("id", { length: 64 }).primaryKey(), productId: varchar("product_id", { length: 64 }).notNull(), comanId: varchar("coman_id", { length: 64 }), producedAt: datetime("produced_at").notNull() });
export const orders = mysqlTable("orders", { id: varchar("id", { length: 64 }).primaryKey(), accountId: varchar("account_id", { length: 64 }).notNull(), appAccountId: varchar("app_account_id", { length: 64 }), placedAt: datetime("placed_at").notNull(), promisedAt: datetime("promised_at"), status: varchar("status", { length: 64 }).notNull(), queuePosition: int("queue_position"), assayGroup: varchar("assay_group", { length: 100 }), companyId: varchar("company_id", { length: 64 }), testingPlatformCompanyId: varchar("testing_platform_company_id", { length: 64 }), limsId: varchar("lims_id", { length: 64 }), paymentStatus: varchar("payment_status", { length: 64 }), ordererId: int("orderer_id"), orderedAt: datetime("ordered_at"), dateReceived: datetime("date_received"), purchaseOrderNumber: varchar("purchase_order_number", { length: 120 }), createdAt: datetime("created_at"), updatedAt: datetime("updated_at"), archivedAt: datetime("archived_at") }, table => [index("orders_company_idx").on(table.companyId), index("orders_app_account_idx").on(table.appAccountId), index("orders_testing_platform_company_idx").on(table.testingPlatformCompanyId)]);
export const tests = mysqlTable("tests", { id: varchar("id", { length: 64 }).primaryKey(), orderId: varchar("order_id", { length: 64 }), lotId: varchar("lot_id", { length: 64 }), assay: varchar("assay", { length: 100 }).notNull(), status: varchar("status", { length: 64 }).notNull(), completedAt: datetime("completed_at"), sampleId: varchar("sample_id", { length: 64 }), assayId: varchar("assay_id", { length: 64 }), turnaroundTimeId: varchar("turnaround_time_id", { length: 64 }), retestOfId: varchar("retest_of_id", { length: 64 }), stabilityStudyTimePointId: varchar("stability_study_time_point_id", { length: 64 }), qbenchState: varchar("qbench_state", { length: 64 }), specStatus: mysqlEnum("spec_status", ["no_spec", "in_spec", "out_spec"]).default("no_spec"), startDate: datetime("start_date"), completeDate: datetime("complete_date"), estimatedStartDate: datetime("estimated_start_date"), estimatedCompleteDate: datetime("estimated_complete_date"), publishedAt: datetime("published_at"), price: decimal("price", { precision: 12, scale: 2 }), notes: text("notes"), laboratoryNotes: text("laboratory_notes"), resultRecipientEmails: json("result_recipient_emails").$type<string[]>(), limsId: varchar("lims_id", { length: 64 }), createdAt: datetime("created_at"), updatedAt: datetime("updated_at"), archivedAt: datetime("archived_at") }, table => [index("tests_sample_idx").on(table.sampleId), index("tests_assay_idx").on(table.assayId)]);
export const results = mysqlTable("results", { id: varchar("id", { length: 64 }).primaryKey(), testId: varchar("test_id", { length: 64 }).notNull(), analyte: varchar("analyte", { length: 100 }).notNull(), value: decimal("value", { precision: 14, scale: 4 }), unit: varchar("unit", { length: 64 }).notNull(), isNonDetect: int("is_non_detect").notNull().default(0), loq: decimal("loq", { precision: 14, scale: 4 }), reportedAt: datetime("reported_at").notNull() });
export const specs = mysqlTable("specs", { id: varchar("id", { length: 64 }).primaryKey(), scope: varchar("scope", { length: 64 }).notNull(), scopeId: varchar("scope_id", { length: 64 }), category: varchar("category", { length: 100 }), analyte: varchar("analyte", { length: 100 }).notNull(), limitValue: decimal("limit_value", { precision: 14, scale: 4 }), limitUnit: varchar("limit_unit", { length: 64 }), source: varchar("source", { length: 100 }).notNull(), citation: text("citation"), isPlaceholder: int("is_placeholder").notNull().default(0) });
export const kbEntries = mysqlTable("kb_entries", { id: varchar("id", { length: 64 }).primaryKey(), questionPattern: varchar("question_pattern", { length: 255 }).notNull(), answer: text("answer").notNull(), author: varchar("author", { length: 160 }).notNull(), approvedBy: varchar("approved_by", { length: 160 }), createdAt: datetime("created_at").notNull() });
export const interactions = mysqlTable("interactions", {
  id: varchar("id", { length: 80 }).primaryKey(), source: varchar("source", { length: 32 }).notNull(), channelRef: varchar("channel_ref", { length: 180 }), externalEventId: varchar("external_event_id", { length: 255 }), sourceSchemaVersion: varchar("source_schema_version", { length: 32 }), threadRef: varchar("thread_ref", { length: 180 }), sourceReceivedAt: datetime("source_received_at"), contactId: varchar("contact_id", { length: 64 }), accountId: varchar("account_id", { length: 64 }), ownerId: varchar("owner_id", { length: 64 }), requestingUserId: int("requesting_user_id"), companyId: varchar("company_id", { length: 64 }), receivedAt: datetime("received_at").notNull(), rawText: text("raw_text").notNull(), intents: json("intents").$type<string[]>(), confidence: decimal("confidence", { precision: 5, scale: 4 }), imminentAction: int("imminent_action").notNull().default(0), classifierMethod: varchar("classifier_method", { length: 40 }).notNull(), baseLane: mysqlEnum("base_lane", ["auto", "assisted", "escalate"]), lane: mysqlEnum("lane", ["auto", "assisted", "escalate"]).notNull(), laneReasons: json("lane_reasons").$type<string[]>().notNull(), gateTrace: json("gate_trace").$type<Array<{ check: string; status: "pass" | "stop" | "not_reached"; read: string }>>(), verifiedReplyStatus: mysqlEnum("verified_reply_status", ["eligible", "ineligible"]).notNull().default("ineligible"), replyGateReasons: json("reply_gate_reasons").$type<string[]>().notNull(), acknowledgment: text("acknowledgment").notNull(), draft: text("draft"), evidence: json("evidence").$type<Array<{ label: string; value: string; source: string; citable: boolean; advisory?: boolean; refusalCode?: string }>>().notNull(), precedent: json("precedent").$type<{ answer: string; author: string; approvedBy?: string | null }>(), knowledgeCitations: json("knowledge_citations").$type<Array<{ sourceId: string; title: string; url: string; anchor: string; score: number; contentHash?: string }>>(), domainComputations: json("domain_computations").$type<Record<string, unknown>>(), resolvedFacts: json("resolved_facts").$type<Record<string, unknown>>(), attachmentsPresent: int("attachments_present").notNull().default(0), sendAllowed: int("send_allowed").notNull().default(0), sendDisabled: int("send_disabled").notNull().default(0), status: mysqlEnum("status", ["open", "awaiting_customer", "auto_resolved", "resolved"]).notNull().default("open"), msToAck: int("ms_to_ack").notNull(), humanMinutesSaved: decimal("human_minutes_saved", { precision: 8, scale: 2 }).notNull().default("0"), queuePriority: int("queue_priority").notNull(), slaMinutes: int("sla_minutes").notNull(), resolvedAt: datetime("resolved_at"), resolvedBy: varchar("resolved_by", { length: 64 }),
}, table => [uniqueIndex("interaction_dedup_unique").on(table.source, table.channelRef), uniqueIndex("interaction_external_event_unique").on(table.source, table.externalEventId), index("interaction_owner_idx").on(table.ownerId, table.lane, table.receivedAt), index("interaction_account_idx").on(table.accountId)]);
export const responseFeedback = mysqlTable("response_feedback", { id: varchar("id", { length: 80 }).primaryKey(), interactionId: varchar("interaction_id", { length: 80 }).notNull(), userId: varchar("user_id", { length: 64 }).notNull(), draftedText: text("drafted_text"), sentText: text("sent_text").notNull(), editRatio: decimal("edit_ratio", { precision: 6, scale: 4 }).notNull(), category: varchar("category", { length: 100 }).notNull(), lane: varchar("lane", { length: 32 }).notNull(), overrideReason: text("override_reason"), createdAt: datetime("created_at").notNull() });
export const clarifications = mysqlTable("clarifications", { id: varchar("id", { length: 80 }).primaryKey(), interactionId: varchar("interaction_id", { length: 80 }).notNull(), question: text("question").notNull(), askedAt: datetime("asked_at").notNull(), answeredAt: datetime("answered_at") });
export const knowledgeSources = mysqlTable("knowledge_sources", {
  id: varchar("id", { length: 96 }).primaryKey(), canonicalUrl: varchar("canonical_url", { length: 500 }).notNull().unique(), title: varchar("title", { length: 300 }).notNull(), sourceType: mysqlEnum("source_type", ["insight", "test_menu", "compliance"]).notNull(), retrievalStatus: mysqlEnum("retrieval_status", ["eligible", "discovery_only", "disabled"]).notNull().default("eligible"), answerSafety: mysqlEnum("answer_safety", ["general_knowledge", "review_required"]).notNull().default("general_knowledge"), discoveryScore: decimal("discovery_score", { precision: 5, scale: 4 }), lastFetchedAt: datetime("last_fetched_at"), createdAt: datetime("created_at").notNull(), updatedAt: datetime("updated_at").notNull(),
}, table => [index("knowledge_sources_status_idx").on(table.retrievalStatus, table.answerSafety)]);
export const knowledgeDocuments = mysqlTable("knowledge_documents", {
  id: varchar("id", { length: 96 }).primaryKey(), sourceId: varchar("source_id", { length: 96 }).notNull(), content: mediumtext("content").notNull(), markdownContent: mediumtext("markdown_content"), contentFormat: mysqlEnum("content_format", ["markdown", "html", "pdf_text", "plain_text"]).notNull().default("plain_text"), parserVersion: varchar("parser_version", { length: 64 }), summaryYaml: text("summary_yaml"), sectionIndex: json("section_index").$type<Array<{ heading: string; anchor: string; excerpt: string }>>(), contentHash: varchar("content_hash", { length: 64 }).notNull(), fetchedAt: datetime("fetched_at").notNull(), indexedAt: datetime("indexed_at").notNull(), status: mysqlEnum("status", ["indexed", "failed", "superseded"]).notNull().default("indexed"),
}, table => [index("knowledge_documents_source_idx").on(table.sourceId, table.status), uniqueIndex("knowledge_document_hash_unique").on(table.sourceId, table.contentHash)]);
export const knowledgeSections = mysqlTable("knowledge_sections", {
  id: varchar("id", { length: 96 }).primaryKey(), documentId: varchar("document_id", { length: 96 }).notNull(), ordinal: int("ordinal").notNull(), headingPath: varchar("heading_path", { length: 1000 }).notNull(), anchor: varchar("anchor", { length: 255 }).notNull(), markdownContent: mediumtext("markdown_content").notNull(), excerpt: text("excerpt").notNull(), tokenCount: int("token_count").notNull(), contentHash: varchar("content_hash", { length: 64 }).notNull(), answerSafety: mysqlEnum("answer_safety", ["general_knowledge", "review_required", "blocked"]).notNull().default("general_knowledge"), effectiveFrom: datetime("effective_from"), effectiveTo: datetime("effective_to"),
}, table => [uniqueIndex("knowledge_section_document_anchor_unique").on(table.documentId, table.anchor), index("knowledge_section_document_ordinal_idx").on(table.documentId, table.ordinal)]);
export const knowledgeRetrievalEvents = mysqlTable("knowledge_retrieval_events", {
  id: varchar("id", { length: 96 }).primaryKey(), queryText: text("query_text").notNull(), interactionId: varchar("interaction_id", { length: 80 }), retrievedAt: datetime("retrieved_at").notNull(), topScore: decimal("top_score", { precision: 5, scale: 4 }).notNull().default("0"), sourceCount: int("source_count").notNull().default(0), gate: mysqlEnum("gate", ["open", "closed"]).notNull(), reasons: json("reasons").$type<string[]>().notNull(),
}, table => [index("knowledge_retrieval_events_interaction_idx").on(table.interactionId, table.retrievedAt)]);
export const hubspotOauthSessions = mysqlTable("hubspot_oauth_sessions", {
  id: varchar("id", { length: 96 }).primaryKey(), stateHash: varchar("state_hash", { length: 64 }).notNull().unique(), codeVerifierEncrypted: text("code_verifier_encrypted").notNull(), requestedByUserId: varchar("requested_by_user_id", { length: 64 }).notNull(), createdAt: datetime("created_at").notNull(), expiresAt: datetime("expires_at").notNull(), usedAt: datetime("used_at"),
}, table => [index("hubspot_oauth_sessions_expiry_idx").on(table.expiresAt)]);
export const hubspotConnections = mysqlTable("hubspot_connections", {
  id: varchar("id", { length: 96 }).primaryKey(), connectedByUserId: varchar("connected_by_user_id", { length: 64 }).notNull(), portalId: varchar("portal_id", { length: 64 }), accessTokenEncrypted: text("access_token_encrypted").notNull(), refreshTokenEncrypted: text("refresh_token_encrypted").notNull(), accessTokenExpiresAt: datetime("access_token_expires_at"), status: mysqlEnum("status", ["active", "revoked", "error"]).notNull().default("active"), connectedAt: datetime("connected_at").notNull(), updatedAt: datetime("updated_at").notNull(),
}, table => [index("hubspot_connections_status_idx").on(table.status, table.updatedAt)]);
export const hubspotContextSnapshots = mysqlTable("hubspot_context_snapshots", {
  id: varchar("id", { length: 96 }).primaryKey(), contactId: varchar("contact_id", { length: 64 }).notNull(), hubspotContactId: varchar("hubspot_contact_id", { length: 64 }).notNull(), sourceObjectIds: json("source_object_ids").$type<string[]>().notNull(), context: json("context").$type<Record<string, unknown>>().notNull(), retrievedAt: datetime("retrieved_at").notNull(), status: mysqlEnum("status", ["available", "unavailable", "error"]).notNull(), errorCode: varchar("error_code", { length: 120 }),
}, table => [index("hubspot_context_contact_idx").on(table.contactId, table.retrievedAt), index("hubspot_context_hubspot_contact_idx").on(table.hubspotContactId, table.retrievedAt)]);

export type User = typeof users.$inferSelect;
export type InsertUser = typeof users.$inferInsert;


export const demoHubspotFieldDefinitions = mysqlTable("demo_hubspot_field_definitions", {
  id: varchar("id", { length: 96 }).primaryKey(), sourceSystem: mysqlEnum("source_system", ["hubspot", "platform", "support"]).notNull().default("hubspot"), objectType: mysqlEnum("object_type", ["companies", "contacts", "deals"]).notNull(), fieldKey: varchar("field_key", { length: 160 }).notNull(), label: varchar("label", { length: 200 }).notNull(), definition: mediumtext("definition").notNull(), dataType: mysqlEnum("data_type", ["text", "number", "date", "url", "boolean"]).notNull().default("text"), searchable: int("searchable").notNull().default(0), writable: int("writable").notNull().default(0), displayedByDefault: int("displayed_by_default").notNull().default(1), sortOrder: int("sort_order").notNull().default(0),
}, table => [uniqueIndex("demo_hubspot_field_unique").on(table.objectType, table.fieldKey), index("demo_hubspot_field_search_idx").on(table.objectType, table.searchable)]);

export const demoTestingPlatformFieldDefinitions = mysqlTable("demo_testing_platform_field_definitions", {
  id: varchar("id", { length: 96 }).primaryKey(), sourceSystem: mysqlEnum("source_system", ["hubspot", "platform", "support"]).notNull().default("platform"), objectType: varchar("object_type", { length: 80 }).notNull(), fieldKey: varchar("field_key", { length: 160 }).notNull(), label: varchar("label", { length: 200 }).notNull(), definition: mediumtext("definition").notNull(), dataType: mysqlEnum("data_type", ["text", "number", "date", "url", "boolean", "json"]).notNull().default("text"), searchable: int("searchable").notNull().default(0), writable: int("writable").notNull().default(0), displayedByDefault: int("displayed_by_default").notNull().default(1), sortOrder: int("sort_order").notNull().default(0),
}, table => [uniqueIndex("demo_platform_field_unique").on(table.objectType, table.fieldKey), index("demo_platform_field_search_idx").on(table.objectType, table.searchable)]);

export const demoSupportFieldDefinitions = mysqlTable("demo_support_field_definitions", {
  id: varchar("id", { length: 96 }).primaryKey(), sourceSystem: mysqlEnum("source_system", ["hubspot", "platform", "support"]).notNull().default("support"), objectType: varchar("object_type", { length: 80 }).notNull(), fieldKey: varchar("field_key", { length: 160 }).notNull(), label: varchar("label", { length: 200 }).notNull(), definition: mediumtext("definition").notNull(), dataType: mysqlEnum("data_type", ["text", "number", "date", "url", "boolean", "json"]).notNull().default("text"), searchable: int("searchable").notNull().default(0), writable: int("writable").notNull().default(0), displayedByDefault: int("displayed_by_default").notNull().default(1), sortOrder: int("sort_order").notNull().default(0),
}, table => [uniqueIndex("demo_support_field_unique").on(table.objectType, table.fieldKey), index("demo_support_field_search_idx").on(table.objectType, table.searchable)]);

export const demoHubspotCompanies = mysqlTable("demo_hubspot_companies", {
  id: varchar("id", { length: 64 }).primaryKey(), accountId: varchar("account_id", { length: 64 }), properties: json("properties").$type<Record<string, string | number | boolean | null>>().notNull(), normalizedName: varchar("normalized_name", { length: 240 }).notNull(), normalizedDomain: varchar("normalized_domain", { length: 240 }), createdAt: datetime("created_at").notNull(), updatedAt: datetime("updated_at").notNull(),
}, table => [index("demo_hubspot_company_name_idx").on(table.normalizedName), index("demo_hubspot_company_domain_idx").on(table.normalizedDomain), index("demo_hubspot_company_account_idx").on(table.accountId)]);

export const demoHubspotContacts = mysqlTable("demo_hubspot_contacts", {
  id: varchar("id", { length: 64 }).primaryKey(), companyId: varchar("company_id", { length: 64 }), accountId: varchar("account_id", { length: 64 }), properties: json("properties").$type<Record<string, string | number | boolean | null>>().notNull(), normalizedName: varchar("normalized_name", { length: 240 }).notNull(), normalizedEmail: varchar("normalized_email", { length: 320 }), normalizedCompany: varchar("normalized_company", { length: 240 }), slackId: varchar("slack_id", { length: 120 }), slackTeamId: varchar("slack_team_id", { length: 64 }), verificationStatus: mysqlEnum("verification_status", ["unverified", "verified", "revoked"]).notNull().default("unverified"), verifiedAt: datetime("verified_at"), createdAt: datetime("created_at").notNull(), updatedAt: datetime("updated_at").notNull(),
}, table => [index("demo_hubspot_contact_name_idx").on(table.normalizedName), index("demo_hubspot_contact_email_idx").on(table.normalizedEmail), index("demo_hubspot_contact_company_idx").on(table.normalizedCompany), uniqueIndex("demo_hubspot_contact_slack_unique").on(table.slackTeamId, table.slackId), index("demo_hubspot_contact_account_idx").on(table.accountId)]);

export const demoHubspotDeals = mysqlTable("demo_hubspot_deals", {
  id: varchar("id", { length: 64 }).primaryKey(), companyId: varchar("company_id", { length: 64 }), accountId: varchar("account_id", { length: 64 }), contactId: varchar("contact_id", { length: 64 }), properties: json("properties").$type<Record<string, string | number | boolean | null>>().notNull(), createdAt: datetime("created_at").notNull(), updatedAt: datetime("updated_at").notNull(),
}, table => [index("demo_hubspot_deal_company_idx").on(table.companyId), index("demo_hubspot_deal_account_idx").on(table.accountId), index("demo_hubspot_deal_contact_idx").on(table.contactId)]);

export const demoHubspotAccessPolicies = mysqlTable("demo_hubspot_access_policies", {
  id: varchar("id", { length: 96 }).primaryKey(), role: mysqlEnum("role", ["admin", "user", "read_only"]).notNull(), objectType: mysqlEnum("object_type", ["companies", "contacts", "deals"]).notNull(), fieldKey: varchar("field_key", { length: 160 }).notNull(), canRead: int("can_read").notNull().default(0), canWrite: int("can_write").notNull().default(0), updatedAt: datetime("updated_at").notNull(),
}, table => [uniqueIndex("demo_hubspot_policy_unique").on(table.role, table.objectType, table.fieldKey)]);

export const demoHubspotVerificationAttempts = mysqlTable("demo_hubspot_verification_attempts", {
  claimId: varchar("claim_id", { length: 96 }).primaryKey(), schemaVersion: varchar("schema_version", { length: 16 }).notNull(), submittedAt: datetime("submitted_at").notNull(), receivedAt: datetime("received_at").notNull(), slackTeamId: varchar("slack_team_id", { length: 64 }).notNull(), slackUserId: varchar("slack_user_id", { length: 120 }).notNull(), payload: json("payload").$type<Record<string, unknown>>().notNull(), status: mysqlEnum("status", ["pending", "verified", "unresolved", "ambiguous", "rejected"]).notNull(), result: json("result").$type<Record<string, unknown>>().notNull(), resolvedContactId: varchar("resolved_contact_id", { length: 64 }), createdAt: datetime("created_at").notNull(), updatedAt: datetime("updated_at").notNull(),
}, table => [index("demo_hubspot_verification_slack_idx").on(table.slackTeamId, table.slackUserId, table.createdAt), index("demo_hubspot_verification_status_idx").on(table.status, table.updatedAt)]);

export const slackAccountBindings = mysqlTable("slack_account_bindings", {
  bindingId: varchar("binding_id", { length: 128 }).primaryKey(), schemaVersion: varchar("schema_version", { length: 16 }).notNull(), requestedAt: datetime("requested_at").notNull(), slackTeamId: varchar("slack_team_id", { length: 64 }).notNull(), slackUserId: varchar("slack_user_id", { length: 120 }).notNull(), slackDisplayName: varchar("slack_display_name", { length: 160 }), claimedFullName: varchar("claimed_full_name", { length: 160 }).notNull(), claimedEmail: varchar("claimed_email", { length: 320 }).notNull(), claimedCompany: varchar("claimed_company", { length: 240 }).notNull(), emailSource: mysqlEnum("email_source", ["slack", "typed"]).notNull(), status: mysqlEnum("status", ["pending", "bound", "conflict", "rejected"]).notNull(), contactId: varchar("contact_id", { length: 64 }), accountId: varchar("account_id", { length: 64 }), conflict: json("conflict").$type<Record<string, unknown>>(), reviewUrl: varchar("review_url", { length: 500 }), message: varchar("message", { length: 500 }), createdAt: datetime("created_at").notNull(), updatedAt: datetime("updated_at").notNull(),
}, table => [index("slack_binding_identity_idx").on(table.slackTeamId, table.slackUserId, table.updatedAt), index("slack_binding_contact_idx").on(table.contactId, table.updatedAt), index("slack_binding_status_idx").on(table.status, table.updatedAt)]);

export const demoHubspotWriteAudits = mysqlTable("demo_hubspot_write_audits", {
  id: varchar("id", { length: 96 }).primaryKey(), actorUserId: varchar("actor_user_id", { length: 64 }), source: varchar("source", { length: 64 }).notNull(), objectType: varchar("object_type", { length: 32 }).notNull(), objectId: varchar("object_id", { length: 64 }).notNull(), fieldKey: varchar("field_key", { length: 160 }), oldValue: json("old_value").$type<unknown>(), newValue: json("new_value").$type<unknown>(), claimId: varchar("claim_id", { length: 96 }), reason: varchar("reason", { length: 255 }).notNull(), createdAt: datetime("created_at").notNull(),
}, table => [index("demo_hubspot_audit_object_idx").on(table.objectType, table.objectId, table.createdAt), index("demo_hubspot_audit_claim_idx").on(table.claimId)]);

export type DemoHubspotFieldDefinition = typeof demoHubspotFieldDefinitions.$inferSelect;
export type DemoHubspotCompany = typeof demoHubspotCompanies.$inferSelect;
export type DemoHubspotContact = typeof demoHubspotContacts.$inferSelect;
export type DemoHubspotDeal = typeof demoHubspotDeals.$inferSelect;
export type DemoHubspotVerificationAttempt = typeof demoHubspotVerificationAttempts.$inferSelect;
