import { trpc } from "@/lib/trpc";
import { Building2, CheckCircle2, Database, GitMerge, Users } from "lucide-react";
import { useEffect, useState } from "react";

export default function AccountMapping() {
  const utils = trpc.useUtils(); const [ownerId, setOwnerId] = useState("");
  const bootstrap = trpc.portfolio.bootstrap.useMutation({ onSuccess: () => { utils.portfolio.owners.invalidate(); } });
  const owners = trpc.portfolio.owners.useQuery();
  useEffect(() => { bootstrap.mutate(); }, []);
  useEffect(() => { if (!ownerId && owners.data?.length) setOwnerId(owners.data.find(owner => owner.id === "owner_sarah")?.id ?? owners.data[0].id); }, [ownerId, owners.data]);
  const portfolio = trpc.portfolio.detail.useQuery({ ownerId }, { enabled: Boolean(ownerId) }); const summary = portfolio.data?.summary;
  return <section className="mx-auto max-w-7xl p-5 md:p-10"><header className="grid gap-6 border-b border-slate-200 pb-8 lg:grid-cols-[1.3fr_.7fr]"><div><p className="eyebrow">OWNER PORTFOLIO & ACCOUNT MAPPING</p><h1 className="mt-2 font-serif text-4xl font-semibold tracking-tight text-slate-950 md:text-5xl">Every account, in the owner’s true portfolio.</h1><p className="mt-4 max-w-3xl text-base leading-7 text-slate-600">Select an AE or AM to see the entire managed book: direct brands, Co-Man accounts, and brands housed within each Co-Man portfolio. The total includes every account an owner is accountable for, including brands assigned beneath a Co-Man.</p></div><aside className="rounded-2xl border border-emerald-200 bg-emerald-50 p-5"><GitMerge className="text-emerald-700" size={22}/><h2 className="mt-4 text-sm font-bold text-emerald-950">Access-control model</h2><p className="mt-2 text-sm leading-6 text-emerald-900">Co-Man contacts receive explicit, brand-level view or edit approval. Their account affiliation alone never grants access to the full Co-Man portfolio.</p></aside></header>
    <section className="mt-7 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><label className="field-label">AM / AE owner</label><select className="field max-w-md" value={ownerId} onChange={event => setOwnerId(event.target.value)} disabled={owners.isLoading}>{owners.data?.map(owner => <option key={owner.id} value={owner.id}>{owner.name} · {owner.role.toUpperCase()}</option>)}</select><p className="mt-3 text-sm text-slate-500">Each demonstration owner has <b>120 direct brands</b>, <b>40 Co-Man accounts</b>, and a complete list of the brands associated to each Co-Man.</p></section>
    <section className="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Summary icon={<Building2 size={19}/>} label="Total managed accounts" value={summary ? String(summary.totalManagedAccounts) : "—"} detail="Direct + Co-Man + portfolio brands"/><Summary icon={<CheckCircle2 size={19}/>} label="Direct brands" value={summary ? String(summary.directBrandCount) : "—"} detail="Owned outside a Co-Man"/><Summary icon={<GitMerge size={19}/>} label="Co-Man accounts" value={summary ? String(summary.comanCount) : "—"} detail="Each contains 5–15 brands"/><Summary icon={<Users size={19}/>} label="Brands under Co-Mans" value={summary ? String(summary.brandsUnderComanCount) : "—"} detail="Shown with contact scope"/></section>
    <section className="mt-7 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-100 px-5 py-4"><div><p className="eyebrow">COMPLETE OWNER PORTFOLIO</p><h2 className="mt-1 font-serif text-2xl font-semibold text-slate-950">{summary ? `${summary.name}'s accounts` : "Loading portfolio…"}</h2></div><span className="badge bg-slate-100 text-slate-700"><Database size={12}/> Demo app data</span></div><div className="max-h-[740px] overflow-auto"><table className="min-w-[1040px] w-full text-sm"><thead className="sticky top-0 bg-white shadow-sm"><tr><th>Account</th><th>Type</th><th>Portfolio relationship</th><th>Contact permissions</th><th>Slack connection</th></tr></thead><tbody>{portfolio.isLoading ? <tr><td colSpan={5} className="py-8 text-center text-slate-500">Loading every owned account…</td></tr> : portfolio.data?.accounts.map(account => <tr key={account.id}><td><b className="text-slate-900">{account.name}</b><span className="mt-1 block font-mono text-xs text-slate-500">{account.id}</span></td><td><span className={`badge ${account.accountType === "Co-Man" ? "bg-violet-100 text-violet-800" : "bg-emerald-100 text-emerald-800"}`}>{account.accountType}</span></td><td className="max-w-sm text-left text-slate-600" style={{ textAlign: "left" }}>{account.portfolio}</td><td className="max-w-sm text-left text-slate-600" style={{ textAlign: "left" }}>{account.contactScope}</td><td className="min-w-48 text-left" style={{ textAlign: "left" }}>{account.verifiedSlackContacts.length ? <span className="badge bg-emerald-100 text-emerald-800"><CheckCircle2 size={12}/> Verified · {account.verifiedSlackContacts.join(", ")}</span> : <span className="text-slate-400">No verified connection</span>}</td></tr>)}</tbody></table></div></section>
    <section className="mt-6 grid gap-4 lg:grid-cols-3"><Rule step="1" title="Owner portfolio" text="The selected AM or AE owns every account in their direct and Co-Man book."/><Rule step="2" title="Co-Man relationship" text="Each Co-Man is associated with between 5 and 15 brands, retained as explicit account relationships."/><Rule step="3" title="Contact permission" text="Each Co-Man contact receives an individual brand scope with view or edit approval instead of broad portfolio access."/></section>
  </section>;
}

function Summary({ icon, label, value, detail }: { icon: React.ReactNode; label: string; value: string; detail: string }) { return <article className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><span className="grid h-9 w-9 place-items-center rounded-xl bg-emerald-50 text-emerald-700">{icon}</span><p className="mt-5 text-xs font-bold uppercase tracking-[.12em] text-slate-500">{label}</p><p className="mt-1 font-serif text-3xl font-semibold text-slate-950">{value}</p><p className="mt-1 text-sm text-slate-500">{detail}</p></article>; }
function Rule({ step, title, text }: { step: string; title: string; text: string }) { return <article className="rounded-2xl border border-slate-200 bg-white p-5"><span className="font-mono text-xs font-bold text-emerald-700">0{step}</span><h2 className="mt-3 text-lg font-bold text-slate-950">{title}</h2><p className="mt-2 text-sm leading-6 text-slate-600">{text}</p></article>; }
