import { accountMappings } from "@/lib/supportDemo";
import { Building2, CheckCircle2, Database, GitMerge, Users } from "lucide-react";

export default function AccountMapping() {
  return <section className="mx-auto max-w-7xl p-5 md:p-10">
    <header className="grid gap-6 border-b border-slate-200 pb-8 lg:grid-cols-[1.3fr_.7fr]">
      <div><p className="eyebrow">IDENTITY & ACCOUNT MAPPING</p><h1 className="mt-2 font-serif text-4xl font-semibold tracking-tight text-slate-950 md:text-5xl">One company record, many verified people.</h1><p className="mt-4 max-w-3xl text-base leading-7 text-slate-600">This table is the operating bridge behind a support response. Slack identities roll up to a company, then resolve against that company’s HubSpot account and Testing Platform account. A company can have multiple verified contacts without creating duplicate customer records.</p></div>
      <aside className="rounded-2xl border border-emerald-200 bg-emerald-50 p-5"><GitMerge className="text-emerald-700" size={22}/><h2 className="mt-4 text-sm font-bold text-emerald-950">Mapping rule</h2><p className="mt-2 text-sm leading-6 text-emerald-900">Slack establishes the sender. HubSpot verifies the contact and company. The Testing Platform supplies operational context only after the company relationship is resolved.</p></aside>
    </header>
    <section className="mt-7 grid gap-4 sm:grid-cols-3"><Summary icon={<Building2 size={19}/>} label="Mapped companies" value="3" detail="Account-level records"/><Summary icon={<Users size={19}/>} label="Verified Slack contacts" value="6" detail="Multiple per company"/><Summary icon={<CheckCircle2 size={19}/>} label="Resolution gate" value="100%" detail="Exact email reviewed"/></section>
    <section className="mt-7 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-100 px-5 py-4"><div><p className="eyebrow">DEMONSTRATION DATA</p><h2 className="mt-1 font-serif text-2xl font-semibold text-slate-950">Company-level identity bridge</h2></div><span className="badge bg-slate-100 text-slate-700"><Database size={12}/> App-owned tables</span></div><div className="overflow-x-auto"><table className="min-w-[980px] w-full text-sm"><thead><tr><th>Company / platform account</th><th>Verified Slack contacts</th><th>HubSpot company</th><th>Connection logic</th></tr></thead><tbody>{accountMappings.map(row => <tr key={row.account}><td><b className="text-slate-900">{row.account}</b><span className="mt-1 block font-mono text-xs text-slate-500">Testing Platform · {row.platformAccount}</span></td><td><div className="flex max-w-xs flex-wrap gap-1.5">{row.contacts.map(contact => <span className="rounded-full bg-emerald-50 px-2 py-1 text-xs font-medium text-emerald-800" key={contact}>{contact}</span>)}</div></td><td><b className="text-slate-800">{row.hubspotCompany}</b><span className="mt-1 block text-xs text-emerald-700">{row.relationship}</span></td><td className="max-w-xs text-slate-600" style={{ textAlign: "left" }}>{row.rule}</td></tr>)}</tbody></table></div></section>
    <section className="mt-6 grid gap-4 lg:grid-cols-3"><Rule step="1" title="Slack identity" text="Workspace and user IDs identify the person who sent the request."/><Rule step="2" title="HubSpot account" text="The person is verified to an exact contact and its company record."/><Rule step="3" title="Platform context" text="A company mapping scopes which orders, tests, and documents can be used for support."/></section>
  </section>;
}

function Summary({ icon, label, value, detail }: { icon: React.ReactNode; label: string; value: string; detail: string }) { return <article className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><span className="grid h-9 w-9 place-items-center rounded-xl bg-emerald-50 text-emerald-700">{icon}</span><p className="mt-5 text-xs font-bold uppercase tracking-[.12em] text-slate-500">{label}</p><p className="mt-1 font-serif text-3xl font-semibold text-slate-950">{value}</p><p className="mt-1 text-sm text-slate-500">{detail}</p></article>; }
function Rule({ step, title, text }: { step: string; title: string; text: string }) { return <article className="rounded-2xl border border-slate-200 bg-white p-5"><span className="font-mono text-xs font-bold text-emerald-700">0{step}</span><h2 className="mt-3 text-lg font-bold text-slate-950">{title}</h2><p className="mt-2 text-sm leading-6 text-slate-600">{text}</p></article>; }
