import { ArrowDown, ArrowRight, Bot, CheckCircle2, Database, LockKeyhole, MessageSquareText, ShieldAlert, UserRoundCheck } from "lucide-react";

const gates = [
  ["Ingest", "Duplicate external_event_id", "Drop duplicate event"],
  ["Identity", "Unresolved sender", "No account context"],
  ["Classify", "Confidence below 0.90", "Cannot be auto"],
  ["Resolve", "Named entity maps to 0 or 2+ records", "Refuse record resolution"],
  ["Verdict", "Shadow computation disagrees with spec_status", "Escalate and show the cause"],
  ["Permission", "Unpublished result or view_results is false", "Strip result evidence"],
  ["Compose + output", "Draft includes a price, citation, or verdict", "Demote before human review"],
] as const;

function Surface({ icon, title, body, note, tone = "border-slate-200 bg-white" }: { icon: React.ReactNode; title: string; body: string; note: string; tone?: string }) {
  return <article className={`rounded-2xl border p-5 shadow-sm ${tone}`}><span className="grid h-9 w-9 place-items-center rounded-xl bg-slate-900 text-white">{icon}</span><h2 className="mt-4 text-lg font-bold text-slate-950">{title}</h2><p className="mt-2 text-sm leading-6 text-slate-600">{body}</p><p className="mt-4 font-mono text-[11px] text-slate-500">{note}</p></article>;
}

export default function Architecture() {
  return <section className="mx-auto max-w-7xl p-5 md:p-10"><header className="max-w-4xl border-b border-slate-300 pb-8"><p className="eyebrow">TAKE-HOME · SYSTEM DESIGN</p><h1 className="mt-3 font-serif text-4xl font-semibold tracking-tight text-slate-950 md:text-5xl">How a customer question becomes a decision packet.</h1><p className="mt-4 text-lg leading-8 text-slate-600">The console creates one missing join: a customer question, the specific test it concerns, and the accountable AE who must act. Every other system keeps its own boundary.</p></header>
    <section className="mt-9"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">TOPOLOGY</p><h2 className="mt-1 font-serif text-3xl font-semibold text-slate-950">The console holds both halves of the join.</h2></div><span className="rounded-full bg-amber-100 px-3 py-1 text-xs font-bold text-amber-900">PYLON · NOT CONNECTED · NEEDS APPROVAL</span></div><div className="mt-5 grid gap-4 xl:grid-cols-[1fr_auto_1.15fr_auto_1fr]"><Surface icon={<MessageSquareText size={17}/>} title="Slack Connect" body="Carries the customer message in and a single fixed acknowledgment back." note="No result values in-channel."/><ArrowRight className="m-auto hidden text-slate-400 xl:block"/><Surface icon={<LockKeyhole size={17}/>} title="Manus triage console" body="Ingests, deduplicates, resolves identity, assembles evidence, applies lane policy, and records the human decision." note="The only join of question + platform record." tone="border-emerald-200 bg-emerald-50"/><ArrowRight className="m-auto hidden text-slate-400 xl:block"/><Surface icon={<UserRoundCheck size={17}/>} title="Account Executive" body="Reviews a demoted case, edits the decision packet, and types the final reply by hand." note="Accountable human."/></div>
      <div className="mt-4 grid gap-4 md:grid-cols-3"><Surface icon={<Database size={17}/>} title="Platform database" body="Read-only system of record for tests, results, limits, partnerships, and permissions." note="spec_status remains authoritative."/><Surface icon={<Bot size={17}/>} title="Claude" body="Closed-enum intent, entity names, and draft wording from facts resolved in code." note="Never sees record IDs or chooses a lane."/><Surface icon={<CheckCircle2 size={17}/>} title="HubSpot" body="Read-only owner, lifecycle, deal, and platform-account context for a verified identity." note="Never a send gate on its own."/></div></section>
    <section className="mt-12 rounded-3xl border border-slate-200 bg-white p-6 shadow-sm md:p-8"><div className="grid gap-6 lg:grid-cols-[1.1fr_.9fr]"><div><p className="eyebrow">WHERE A REQUEST CAN BE STOPPED</p><h2 className="mt-2 font-serif text-3xl font-semibold text-slate-950">Seven gates. One direction.</h2><p className="mt-3 max-w-2xl leading-7 text-slate-600">Every failure may demote an interaction to assisted review or escalation. No failure ever promotes an interaction to a faster lane.</p><div className="mt-6 space-y-3">{gates.map(([title, condition, outcome], index) => <div key={title} className="grid gap-2 rounded-xl border border-slate-200 bg-slate-50 p-4 sm:grid-cols-[auto_1fr_auto] sm:items-center"><span className="grid h-7 w-7 place-items-center rounded-full bg-slate-900 text-xs font-bold text-white">{index + 1}</span><div><p className="font-semibold text-slate-950">{title}</p><p className="font-mono text-xs text-slate-500">{condition}</p></div><span className="text-sm font-semibold text-amber-800">{outcome}</span></div>)}</div></div><aside className="rounded-2xl bg-slate-950 p-6 text-slate-100"><ShieldAlert className="text-amber-300" size={21}/><p className="mt-5 text-xs font-black tracking-[.16em] text-emerald-300">DEMOTION BUS</p><h3 className="mt-2 text-2xl font-semibold">No arrow runs the other way.</h3><p className="mt-4 text-sm leading-6 text-slate-300">The stored platform verdict is never overridden. A separate computation is only a shadow check: when it disagrees, the case escalates with the reason shown to the AE.</p><div className="my-6 flex flex-col items-center gap-1 text-slate-400"><ArrowDown size={17}/><ArrowDown size={17}/><ArrowDown size={17}/></div><div className="rounded-xl border border-white/10 bg-white/5 p-4 text-sm leading-6 text-slate-200"><b className="block text-white">Slack output boundary</b>The permissive bridge accepts an authenticated incoming event. The only outbound Slack content is the fixed acknowledgment; result values and model-authored response text remain out of channel.</div></aside></div></section>
  </section>;
}
