import { Activity, Gauge, Sigma } from "lucide-react";
import { useMemo, useState } from "react";
import { trpc } from "@/lib/trpc";

export default function Capacity() {
  const [n, setN] = useState(.05); const [d, setD] = useState(.68); const [t, setT] = useState(6.7); const input = useMemo(() => ({ n, d, t }), [n, d, t]); const capacity = trpc.prototype.capacity.useQuery(input); const result = capacity.data?.multiple ?? 0; const ceiling = capacity.data?.ceiling ?? 0; const points = capacity.data?.points ?? []; const max = Math.max(ceiling, ...points.map(point => point.value));
  return <section className="mx-auto max-w-7xl p-5 md:p-10"><header className="flex flex-wrap items-end justify-between gap-5"><div><p className="eyebrow">CAPACITY INSTRUMENTATION</p><h1 className="mt-2 font-serif text-4xl font-semibold tracking-tight text-slate-950">Capacity, without circular metrics.</h1><p className="mt-3 max-w-2xl text-slate-600">Every figure below is assumption-based until shadow-mode handling data exists. Edit ratio remains the observed learning signal; it never promotes an automation category.</p></div><span className="rounded-full bg-amber-100 px-3 py-1 text-xs font-bold text-amber-900">ASSUMPTION-BASED</span></header><div className="mt-8 grid gap-4 sm:grid-cols-3"><Metric icon={<Activity size={18}/>} label="Capacity multiple" value={`${result.toFixed(1)}×`}/><Metric icon={<Gauge size={18}/>} label="Amdahl ceiling" value={`${ceiling.toFixed(1)}×`}/><Metric icon={<Sigma size={18}/>} label="Throughput input" value={`${t.toFixed(1)}×`}/></div><div className="mt-6 grid gap-6 lg:grid-cols-[.9fr_1.1fr]"><section className="panel"><h2>Named inputs</h2><p className="mt-2 font-mono text-sm text-slate-600">{capacity.data?.formula ?? "1 / (n + (1 − n) × (1 − d) / T)"}</p><Slider label="Non-scaling AE time (n)" value={n} min={.02} max={.4} step={.01} display={`${Math.round(n * 100)}%`} onChange={setN}/><Slider label="Deflection rate (d)" value={d} min={0} max={.9} step={.01} display={`${Math.round(d * 100)}%`} onChange={setD}/><Slider label="Per-item throughput (T)" value={t} min={1} max={8} step={.1} display={`${t.toFixed(1)}×`} onChange={setT}/></section><section className="panel"><h2>Throughput curve and ceiling</h2><div className="relative mt-7 h-64 rounded-xl border border-slate-200 bg-slate-50 p-5"><div className="absolute inset-x-5 top-5 border-t border-dashed border-amber-500"><span className="-mt-5 inline-block bg-slate-50 pr-2 text-xs font-semibold text-amber-800">Ceiling {ceiling.toFixed(1)}×</span></div><svg className="h-full w-full" viewBox="0 0 800 200" preserveAspectRatio="none" aria-label="Capacity multiple curve"><polyline fill="none" stroke="#047857" strokeWidth="5" points={points.map((point, index) => `${(index / Math.max(1, points.length - 1)) * 760 + 20},${180 - (point.value / Math.max(1, max)) * 145}`).join(" ")} /></svg></div><div className="mt-3 flex justify-between text-xs text-slate-500"><span>Lower throughput</span><span>Higher throughput</span></div></section></div><section className="panel mt-6"><h2>Observed learning loop</h2><p className="mt-2 text-sm text-slate-600">No reviewed sends have been aggregated by this prototype yet. When present, edit-ratio observations should inform human policy review, not automatically modify the frozen lane table.</p></section></section>;
}
function Slider({ label, value, min, max, step, display, onChange }: { label: string; value: number; min: number; max: number; step: number; display: string; onChange: (value: number) => void }) { return <label className="mt-6 block"><span className="flex justify-between text-sm font-semibold text-slate-800"><span>{label}</span><span className="font-mono text-emerald-700">{display}</span></span><input className="mt-3 w-full accent-emerald-700" type="range" min={min} max={max} step={step} value={value} onChange={event => onChange(Number(event.target.value))}/></label>; }
function Metric({ icon, label, value }: { icon: React.ReactNode; label: string; value: string }) { return <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><span className="flex h-9 w-9 items-center justify-center rounded-lg bg-emerald-100 text-emerald-800">{icon}</span><p className="mt-5 text-xs font-bold uppercase tracking-[.12em] text-slate-500">{label}</p><p className="mt-1 font-serif text-4xl font-semibold text-slate-950">{value}</p></div>; }
