import { useState } from "react";
import { CheckCircle2, Search, ShieldCheck } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import { toast } from "sonner";

type Candidate = { id: string; name: string; email: string | null; company: string | null };

export default function ContactMapping() {
  const mappings = trpc.hubspot.contactMappings.useQuery();
  const accounts = trpc.hubspot.mappingAccounts.useQuery();
  const externalCandidates = trpc.hubspot.externalSlackCandidates.useQuery();
  const [candidates, setCandidates] = useState<Record<string, Candidate[]>>({});
  const [newContact, setNewContact] = useState({ accountId: "", name: "", email: "", slackWorkspaceId: "", slackUserId: "" });
  const search = trpc.hubspot.searchContactsByEmail.useMutation({ onSuccess: (data, variables) => setCandidates(current => ({ ...current, [variables.email]: data })), onError: error => toast.error(error.message) });
  const refresh = trpc.hubspot.refreshVerifiedContact.useMutation({ onSuccess: () => { toast.success("Verified mapping and current HubSpot context saved."); mappings.refetch(); externalCandidates.refetch(); }, onError: error => toast.error(`Contact mapped, but HubSpot context could not be refreshed: ${error.message}`) });
  const map = trpc.hubspot.verifyAndMapContact.useMutation({ onSuccess: (_result, variables) => { refresh.mutate(variables); }, onError: error => toast.error(error.message) });
  const add = trpc.hubspot.addPendingContact.useMutation({ onSuccess: () => { toast.success("Contact added. Find the exact HubSpot email to complete verification."); setNewContact({ accountId: "", name: "", email: "", slackWorkspaceId: "", slackUserId: "" }); mappings.refetch(); }, onError: error => toast.error(error.message) });
  return <section className="mx-auto max-w-6xl p-5 md:p-10"><p className="text-xs font-bold tracking-[.16em] text-[#517263]">IDENTITY GOVERNANCE</p><h1 className="mt-2 font-serif text-4xl font-semibold tracking-tight">Verified contact mapping</h1><p className="mt-3 max-w-3xl text-[#60766c]">A customer Slack message receives CRM context only when its Slack workspace and user are tied to this exact Light Labs account contact and the matching HubSpot email record. No name matching or fuzzy identity resolution is allowed. A successful match immediately saves a fresh, read-only HubSpot context snapshot.</p>
    <div className="panel mt-6"><h2>Unmapped customer senders</h2><p className="mt-1 text-sm text-[#60766c]">These are source-provided Slack identifiers from externally classified bridge events. They are not customer names or emails. Choose <b>Use for mapping</b>, then confirm the real customer identity and exact HubSpot email below.</p>{externalCandidates.isLoading ? <p className="mt-4 text-sm text-[#60766c]">Loading pending customer identities…</p> : externalCandidates.data?.length ? <div className="mt-4 overflow-x-auto"><table className="min-w-full text-sm"><thead><tr><th>Slack identity</th><th>Last conversation</th><th>External signal</th><th>Last seen</th><th className="text-right">Action</th></tr></thead><tbody>{externalCandidates.data.map(candidate => <tr key={candidate.id}><td><b>{candidate.slackWorkspaceId}</b><span className="block text-xs text-[#60766c]">{candidate.slackUserId}</span></td><td>{candidate.lastChannelId ?? "—"}<span className="block text-xs text-[#60766c]">{candidate.lastChannelType ?? "Unknown type"}</span></td><td>{candidate.externallySharedChannel ? <span className="text-[#176344]">Shared/external channel</span> : <span className="text-[#9a5b00]">Explicit external event</span>}</td><td>{new Date(candidate.lastSeenAt).toLocaleString()}</td><td className="text-right"><Button size="sm" variant="outline" onClick={() => { setNewContact(current => ({ ...current, slackWorkspaceId: candidate.slackWorkspaceId, slackUserId: candidate.slackUserId })); document.getElementById("add-customer-identity")?.scrollIntoView({ behavior: "smooth", block: "center" }); }}>Use for mapping</Button></td></tr>)}</tbody></table></div> : <p className="mt-4 rounded-lg bg-[#f7faf7] p-3 text-sm text-[#60766c]">No externally classified first-contact senders are pending. A real Bobby bridge event with an externality signal will appear here.</p>}</div>
    <div id="add-customer-identity" className="panel mt-6"><h2>Add a customer Slack identity</h2><p className="mt-1 text-sm text-[#60766c]">Create the contact from the customer’s exact email, Slack workspace ID, and Slack user ID. Then use the table below to confirm the matching HubSpot record.</p><div className="mt-4 grid gap-3 md:grid-cols-2 lg:grid-cols-3"><select className="h-10 rounded-md border border-input bg-background px-3 text-sm" value={newContact.accountId} onChange={event => setNewContact(current => ({ ...current, accountId: event.target.value }))}><option value="">Select Light Labs account</option>{accounts.data?.map(account => <option key={account.id} value={account.id}>{account.name}</option>)}</select><Input placeholder="Customer full name" value={newContact.name} onChange={event => setNewContact(current => ({ ...current, name: event.target.value }))}/><Input placeholder="Verified customer email" value={newContact.email} onChange={event => setNewContact(current => ({ ...current, email: event.target.value }))}/><Input placeholder="Slack workspace ID (T…)" value={newContact.slackWorkspaceId} onChange={event => setNewContact(current => ({ ...current, slackWorkspaceId: event.target.value }))}/><Input placeholder="Slack user ID (U…)" value={newContact.slackUserId} onChange={event => setNewContact(current => ({ ...current, slackUserId: event.target.value }))}/><Button onClick={() => add.mutate(newContact)} disabled={add.isPending}>{add.isPending ? "Adding…" : "Add for verification"}</Button></div></div>
    <div className="panel mt-8 overflow-x-auto"><table className="min-w-full text-sm"><thead><tr><th>Light Labs account & contact</th><th>Verified Slack identity</th><th>HubSpot status</th><th className="text-right">Action</th></tr></thead><tbody>{mappings.isLoading ? <tr><td colSpan={4} className="py-8 text-center text-[#60766c]">Loading verified contacts…</td></tr> : mappings.data?.map(contact => <tr key={contact.id}><td><b>{contact.name}</b><span className="block text-xs text-[#60766c]">{contact.email} · {contact.accountName}</span></td><td>{contact.slackWorkspaceId && contact.slackUserId ? <span className="inline-flex items-center gap-1 text-[#176344]"><ShieldCheck size={14}/> {contact.slackWorkspaceId} / {contact.slackUserId}</span> : <span className="text-[#9a5b00]">Not provisioned</span>}</td><td>{contact.hubspotContactId && /^\d+$/.test(contact.hubspotContactId) ? <span className="inline-flex items-center gap-1 text-[#176344]"><CheckCircle2 size={14}/> Verified · {contact.hubspotContactId}</span> : <span className="text-[#9a5b00]">Needs exact email match</span>}<div className="mt-2 space-y-1">{(candidates[contact.email ?? ""] ?? []).map(candidate => <button className="block rounded border border-[#c5d7ca] px-2 py-1 text-left text-xs hover:bg-[#e7f6eb]" key={candidate.id} onClick={() => map.mutate({ contactId: contact.id, hubspotContactId: candidate.id })}>Use {candidate.name} · {candidate.email}</button>)}</div></td><td className="text-right">{contact.email && <Button size="sm" variant="outline" disabled={search.isPending} onClick={() => search.mutate({ email: contact.email! })}><Search size={14} className="mr-2"/>Find exact HubSpot email</Button>}</td></tr>)}</tbody></table></div>
    <div className="mt-5 rounded-xl border border-[#d5e1d8] bg-[#edf7ef] p-4 text-sm text-[#295640]"><b>Why this is required:</b> HubSpot enrichment can enrich a ticket; it cannot establish who sent a Slack message. This screen creates the reviewed identity bridge before any CRM data is used in triage.</div>
  </section>;
}
