import { trpc } from "@/lib/trpc";
import { AlertTriangle, ChevronRight, CircleGauge, FlaskConical, Play, RefreshCw, ShieldCheck } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { useLocation } from "wouter";
import { toast } from "sonner";

const viewers = [{ id: "usr_sarah", name: "Sarah Chen", role: "AE" }, { id: "usr_marcus", name: "Marcus Reid", role: "AE" }, { id: "usr_admin", name: "Demo Admin", role: "Admin" }] as const;
const lanes = ["all", "escalate", "assisted", "auto"] as const;
const laneClass: Record<string, string> = { auto: "bg-[#bdeecb] text-[#104d31]", assisted: "bg-[#ffe0a0] text-[#704b00]", escalate: "bg-[#ffc6bd] text-[#7c2014]" };
const age = (date: Date | string) => { const min = Math.max(0, Math.round((Date.now() - new Date(date).getTime()) / 60000)); return min < 1 ? "now" : min < 60 ? `${min}m` : `${Math.floor(min / 60)}h`; };

export default function Home() { const [, setLocation] = useLocation(); const params = useMemo(() => new URLSearchParams(window.location.search), []); const [viewer, setViewer] = useState<(typeof viewers)[number]["id"]>((params.get("viewer") as (typeof viewers)[number]["id"]) || "usr_sarah"); const [lane, setLane] = useState<(typeof lanes)[number]>("all"); const utils = trpc.useUtils(); const boot = trpc.triage.bootstrap.useMutation(); const queue = trpc.triage.queue.useQuery({ viewerId: viewer, lane: lane === "all" ? undefined : lane }); const fixtures = trpc.triage.fixtures.useQuery(); const runFixture = trpc.triage.runFixture.useMutation({ onSuccess: data => { utils.triage.queue.invalidate(); setLocation(`/interactions/${data.interaction.id}?viewer=${viewer}`); }, onError: error => toast.error(error.message) });
  useEffect(() => { boot.mutate(); }, []);
  const changeViewer = (next: typeof viewer) => { setViewer(next); window.history.replaceState({}, "", `/?viewer=${next}`); };
  return <section className="mx-auto max-w-7xl p-5 md:p-10"><header className="flex flex-wrap items-start justify-between gap-5"><div><p className="text-xs font-bold tracking-[.16em] text-[#517263]">LIGHT LABS · SAFETY-FIRST OPERATIONS</p><h1 className="mt-2 font-serif text-4xl font-semibold tracking-tight md:text-5xl">Decision-ready queue</h1><p className="mt-3 max-w-2xl text-[#60766c]">Every interaction has verified context, traceable evidence, and an explicit automation boundary before an AE sees it.</p></div><div className="flex items-center gap-3 rounded-xl border border-[#d4ded6] bg-white px-3 py-2 shadow-sm"><span className="text-xs font-semibold text-[#60766c]">Viewing as</span><select value={viewer} onChange={event => changeViewer(event.target.value as typeof viewer)} className="bg-transparent text-sm font-semibold outline-none">{viewers.map(item => <option value={item.id} key={item.id}>{item.name} · {item.role}</option>)}</select></div></header>
    <div className="mt-8 grid gap-4 lg:grid-cols-[1fr_230px]"><div className="rounded-2xl border border-[#d6ded7] bg-white p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex flex-wrap gap-2">{lanes.map(item => <button key={item} className={`filter-chip ${lane === item ? "filter-chip-active" : ""}`} onClick={() => setLane(item)}>{item === "all" ? "All lanes" : item[0].toUpperCase() + item.slice(1)}</button>)}</div><button className="inline-flex items-center gap-2 text-sm font-semibold text-[#176344]" onClick={() => queue.refetch()}><RefreshCw size={15}/>Refresh</button></div><div className="mt-5 overflow-x-auto"><table className="queue-table"><thead><tr><th>Account</th><th>Contact</th><th>Tier</th><th>Lane</th><th>Category</th><th>Age</th><th>SLA</th><th>Confidence</th><th></th></tr></thead><tbody>{queue.isLoading ? <tr><td colSpan={9} className="py-8 text-center text-[#60766c]">Hydrating queue…</td></tr> : queue.data?.length ? queue.data.map(row => <tr key={row.id} className="cursor-pointer" onClick={() => setLocation(`/interactions/${row.id}?viewer=${viewer}`)}><td className="font-semibold">{row.accountName}</td><td>{row.contactName}</td><td>{row.accountTier}</td><td><span className={`lane-badge ${laneClass[row.lane]}`}>{row.lane.toUpperCase()}</span></td><td>{row.intents?.join(" + ")}</td><td>{age(row.receivedAt)}</td><td>{row.status === "resolved" || row.status === "auto_resolved" ? "Resolved" : `${row.slaMinutes}m`}</td><td><span className="font-semibold">{Math.round(Number(row.confidence) * 100)}%</span><span className="block text-[10px] text-[#60766c]">non-dispositive</span></td><td><ChevronRight size={17} className="text-[#799087]"/></td></tr>) : <tr><td colSpan={9} className="py-8 text-center text-[#60766c]">No matching items. Run an Appendix A scenario to populate this queue.</td></tr>}</tbody></table></div></div><aside className="rounded-2xl bg-[#123f2f] p-5 text-white"><ShieldCheck size={22} className="text-[#a9edc5]"/><p className="mt-5 text-xs font-bold tracking-[.16em] text-[#a9edc5]">LIVE SAFETY STATE</p><p className="mt-2 text-2xl font-semibold">No blind sends.</p><p className="mt-3 text-sm leading-6 text-[#c2d8c9]">Placeholders block actions. Escalations need a persisted human override. Confidence only demotes.</p><button className="mt-6 inline-flex items-center gap-2 text-sm font-semibold text-[#a9edc5]" onClick={() => setLocation("/capacity")}><CircleGauge size={16}/>View capacity instrumentation</button></aside></div>
    <section className="mt-6 rounded-2xl border border-[#b9dfc3] bg-[#eaf8ee] p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2"><FlaskConical size={19} className="text-[#176344]"/><h2 className="font-serif text-2xl font-semibold">Appendix A live demo</h2></div><p className="mt-2 max-w-3xl text-sm text-[#476358]">Runs all eight verified fixtures with injected classifications. It demonstrates deterministic routing and safety controls without requiring a live model call.</p></div><span className="rounded-full border border-[#abd7b7] bg-white px-3 py-1 text-xs font-bold text-[#176344]">Demo mode</span></div><div className="mt-4 flex flex-wrap gap-2">{fixtures.data?.map(fixture => <button key={fixture.id} className="demo-button" onClick={() => runFixture.mutate({ fixtureId: fixture.id })} disabled={runFixture.isPending}><Play size={13}/>Run {fixture.id}: {fixture.lane}</button>)}</div></section>
    <footer className="mt-8 flex flex-wrap gap-x-6 gap-y-2 border-t border-[#d6ded7] pt-5 text-xs text-[#60766c]"><span>Ingest-only Slack integration</span><span>Numeric comparisons use stored records</span><span>Human judgment remains accountable</span></footer></section>; }
