import HubSpotConnectionCard from "@/components/HubSpotConnectionCard";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import { Database, ExternalLink, PlugZap, ShieldCheck, Waypoints } from "lucide-react";
import { useState } from "react";
import { useLocation } from "wouter";
import { toast } from "sonner";

function LimsConnectionCard() {
  const status = trpc.lims.status.useQuery();
  if (status.isLoading) return <div className="panel">Loading LIMS connection state…</div>;
  if (!status.data) return <div className="panel">Unable to load the LIMS connection state.</div>;
  return <section className="panel"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex items-center gap-2"><Database size={18} className="text-violet-700"/><h2>QBench LIMS connection</h2></div><p className="mt-2 text-sm text-slate-600">Visible as a connection for workflow design; its current payload is intentionally simulated.</p></div><span className="badge bg-violet-100 text-violet-800">DEMO DATA</span></div><div className="mt-4 grid gap-3 sm:grid-cols-3"><div className="rounded-lg bg-slate-50 p-3"><p className="eyebrow">Connection health</p><p className="mt-1 font-semibold text-emerald-800">{status.data.status}</p></div><div className="rounded-lg bg-slate-50 p-3"><p className="eyebrow">Operating mode</p><p className="mt-1 font-semibold text-slate-800">{status.data.mode}</p></div><div className="rounded-lg bg-slate-50 p-3"><p className="eyebrow">Last simulated sync</p><p className="mt-1 font-semibold text-slate-800">{new Date(status.data.lastSyncedAt).toLocaleString()}</p></div></div><p className="mt-4 rounded-lg bg-violet-50 p-3 text-xs leading-5 text-violet-950"><b>Boundary:</b> {status.data.disclaimer}</p><div className="mt-4 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr><th>External ID</th><th>Entity</th><th>Record</th><th>State</th></tr></thead><tbody>{status.data.records.map(record => <tr className="border-t border-slate-100" key={record.externalId}><td className="py-2 font-mono text-xs">{record.externalId}</td><td>{record.entity}</td><td>{record.label}</td><td>{record.state.replaceAll("_", " ")}</td></tr>)}</tbody></table></div></section>;
}

function IdentityWriteTool() {
  const [, navigate] = useLocation(); const accounts = trpc.hubspot.mappingAccounts.useQuery();
  const [draft, setDraft] = useState({ accountId: "", name: "", email: "", slackWorkspaceId: "", slackUserId: "" });
  const write = trpc.identity.writePending.useMutation({ onSuccess: () => { toast.success("Identity staged for exact HubSpot-email verification."); setDraft({ accountId: "", name: "", email: "", slackWorkspaceId: "", slackUserId: "" }); }, onError: error => toast.error(error.message) });
  const update = (key: keyof typeof draft, value: string) => setDraft(current => ({ ...current, [key]: value }));
  return <section className="panel"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2"><ShieldCheck size={18} className="text-emerald-700"/><h2>Identity write tool</h2></div><p className="mt-2 text-sm text-slate-600">Creates a pending Slack identity record. It cannot verify or enrich a customer until an exact HubSpot email match is confirmed.</p></div><span className="badge bg-amber-100 text-amber-900">ADMIN WRITE</span></div><div className="mt-4 grid gap-3 md:grid-cols-2"><select className="field" value={draft.accountId} onChange={event => update("accountId", event.target.value)}><option value="">Select Light Labs account</option>{accounts.data?.map(account => <option key={account.id} value={account.id}>{account.name}</option>)}</select><Input placeholder="Customer full name" value={draft.name} onChange={event => update("name", event.target.value)}/><Input placeholder="Verified customer email" value={draft.email} onChange={event => update("email", event.target.value)}/><Input placeholder="Slack workspace ID (T…)" value={draft.slackWorkspaceId} onChange={event => update("slackWorkspaceId", event.target.value)}/><Input placeholder="Slack user ID (U…)" value={draft.slackUserId} onChange={event => update("slackUserId", event.target.value)}/><Button disabled={write.isPending || Object.values(draft).some(value => !value)} onClick={() => write.mutate(draft)}>{write.isPending ? "Writing…" : "Stage identity write"}</Button></div><button className="mt-4 inline-flex items-center gap-2 text-sm font-semibold text-emerald-700" onClick={() => navigate("/integrations/slack")}>Manage bridge policy <ExternalLink size={14}/></button></section>;
}

export default function Integrations() {
  const [, navigate] = useLocation();
  return <section className="mx-auto max-w-6xl p-5 md:p-10"><p className="eyebrow">CONNECTIONS</p><h1 className="mt-2 font-serif text-4xl font-semibold tracking-tight text-slate-950">Integration control plane</h1><p className="mt-3 max-w-3xl text-slate-600">HubSpot provides verified CRM context, the bridge captures inbound Slack events, and the LIMS panel makes laboratory-system boundaries explicit. Connections add evidence; they never independently promote a response to sendable.</p><div className="mt-8 grid gap-5 lg:grid-cols-2"><section className="panel"><div className="flex items-center gap-2"><PlugZap size={18} className="text-emerald-700"/><h2>Permissive customer bridge</h2></div><p className="mt-2 text-sm text-slate-600">Authenticated bridge events with a workspace identifier are accepted by default unless a channel is explicitly disabled or assigned to native Slack. All activity is audited.</p><Button className="mt-4" onClick={() => navigate("/integrations/slack")}>Open bridge controls</Button></section><section className="panel"><div className="flex items-center gap-2"><Waypoints size={18} className="text-blue-700"/><h2>HubSpot enrichment</h2></div><p className="mt-2 text-sm text-slate-600">OAuth-backed, read-only CRM retrieval is available only after an administrator connects and verifies the HubSpot MCP session.</p><Button className="mt-4" variant="outline" onClick={() => navigate("/integrations/hubspot")}>Open HubSpot setup</Button><Button className="mt-4 ml-2" onClick={() => navigate("/integrations/demo-hubspot")}>Open demo CRM</Button></section></div><div className="mt-5"><IdentityWriteTool /></div><div className="mt-5"><LimsConnectionCard /></div></section>;
}
