import { useState } from "react";
import { trpc } from "@/lib/trpc";
import { Search } from "lucide-react";

export default function KnowledgeLibrary() {
  const [query, setQuery] = useState(""); const [selectedSourceId, setSelectedSourceId] = useState("k_compliance"); const [sectionAnchor, setSectionAnchor] = useState("");
  const sources = trpc.knowledge.sources.useQuery();
  const search = trpc.knowledge.search.useQuery({ query: query.length >= 3 ? query : "testing", limit: 5 });
  const document = trpc.knowledge.document.useQuery({ sourceId: selectedSourceId }, { enabled: Boolean(selectedSourceId) });
  const section = trpc.knowledge.section.useQuery({ sourceId: selectedSourceId, anchor: sectionAnchor }, { enabled: Boolean(selectedSourceId && sectionAnchor) });
  return <section className="mx-auto max-w-7xl p-5 md:p-10"><p className="text-xs font-bold tracking-[.16em] text-ink-soft">ATTRIBUTABLE KNOWLEDGE</p><h1 className="mt-2 font-serif text-4xl font-semibold tracking-tight">Knowledge, planned before read</h1><p className="mt-3 max-w-3xl text-ink-muted">Each approved URL is a source; each fetched version is its document. Agents begin with relevance, a compact YAML-style plan, and section headings before opening only the cited Markdown section they need.</p>
    <div className="panel mt-7"><label className="text-xs font-black uppercase tracking-[.12em] text-ink-muted">Plan a retrieval</label><div className="mt-2 flex gap-2"><Search size={18} className="mt-2.5 text-ink-muted"/><input value={query} onChange={event => setQuery(event.target.value)} placeholder="e.g. allergen testing turnaround" className="w-full border-0 bg-transparent py-2 text-sm outline-none"/></div>{query.length >= 3 && <div className="mt-4 grid gap-3 md:grid-cols-2">{search.data?.plans.map(plan => <button key={plan.sourceId} onClick={() => { setSelectedSourceId(plan.sourceId); setSectionAnchor(plan.relevantSections[0]?.anchor ?? ""); }} className="rounded-lg border border-line-strong bg-sunken p-4 text-left"><p className="font-semibold">{plan.title}</p><pre className="mt-2 max-h-40 overflow-auto whitespace-pre-wrap text-xs text-ink-soft">{plan.summaryYaml ?? "Summary pending refresh"}</pre><p className="mt-3 text-xs font-semibold text-ok">{plan.relevantSections.length} relevant section{plan.relevantSections.length === 1 ? "" : "s"} available</p></button>)}</div>}</div>
    <div className="mt-5 grid gap-5 md:grid-cols-2"><article className="panel"><h2>Approved source catalog</h2><p className="mt-1 text-sm text-ink-muted">{sources.data?.length ?? 0} Light Labs URLs. Source policy stays separate from fetched content and its version history.</p><div className="mt-4 max-h-[42rem] space-y-2 overflow-auto pr-1">{sources.data?.map(source => <button key={source.id} onClick={() => { setSelectedSourceId(source.id); setSectionAnchor(""); }} className={`w-full rounded-lg border p-3 text-left text-sm ${selectedSourceId === source.id ? "border-ok-line-strong bg-ok-soft" : "border-line bg-panel"}`}><b>{source.title}</b><span className="mt-1 block text-xs text-ink-muted">{source.sourceType} · {source.documentCount} indexed version</span></button>)}</div></article><article className="panel"><h2>{document.data?.source.title ?? "Select a source"}</h2>{document.data?.document ? <><p className="mt-1 text-xs text-ink-muted">Canonical source: <a className="text-ok underline" href={document.data.source.canonicalUrl} target="_blank" rel="noreferrer">{document.data.source.canonicalUrl}</a></p><h3 className="mt-5">YAML-style retrieval summary</h3><pre className="message mt-2 max-h-64 overflow-auto whitespace-pre-wrap">{document.data.document.summaryYaml}</pre><h3 className="mt-5">Read a cited section</h3><div className="mt-2 flex flex-wrap gap-2">{document.data.document.sectionIndex?.map(entry => <button key={entry.anchor} onClick={() => setSectionAnchor(entry.anchor)} className={`rounded-full px-3 py-1 text-xs ${sectionAnchor === entry.anchor ? "bg-ok text-white" : "bg-ok-soft text-ok"}`}>{entry.heading}</button>)}</div>{section.data?.section && <pre className="message mt-4 max-h-[28rem] overflow-auto whitespace-pre-wrap">{section.data.section.markdown}</pre>}<details className="mt-5 text-sm"><summary className="cursor-pointer font-semibold text-ok">Show full Markdown document</summary><pre className="message mt-3 max-h-[36rem] overflow-auto whitespace-pre-wrap">{document.data.document.markdown}</pre></details></> : <p className="mt-4 text-sm text-ink-muted">Choose an approved source to inspect its compact plan and targeted sections.</p>}</article></div>
  </section>;
}
