import { trpc } from "@/lib/trpc";
import { ArrowLeft, BadgeAlert, CheckCircle2, Copy, LockKeyhole, ShieldAlert } from "lucide-react";
import { useState } from "react";
import { useLocation, useRoute } from "wouter";
import { toast } from "sonner";

const laneColor: Record<string, string> = { auto: "bg-emerald-100 text-emerald-800", assisted: "bg-amber-100 text-amber-900", escalate: "bg-rose-100 text-rose-800" };
export default function PrototypeInteraction() {
  const [, params] = useRoute("/interactions/:id"); const [, navigate] = useLocation(); const [copied, setCopied] = useState(false);
  const itemQuery = trpc.prototype.item.useQuery({ id: params?.id ?? "" }); const item = itemQuery.data;
  if (itemQuery.isLoading) return <div className="p-10 text-sm text-slate-500">Loading canonical interaction…</div>;
  if (!item) return <section className="p-10"><button onClick={() => navigate("/")} className="text-sm font-semibold text-emerald-700">Back to console</button><h1 className="mt-5 text-3xl font-semibold">Interaction not found</h1></section>;
  const evidence = item.evidence ?? []; const citations = item.knowledgeCitations ?? []; const computations = item.domainComputations as Record<string, unknown> | null;
  const copy = async () => { await navigator.clipboard.writeText(item.draft ?? item.acknowledgment); setCopied(true); toast.success("Draft copied for a human to send externally."); };
  return <section className="mx-auto max-w-7xl p-5 md:p-10"><button className="inline-flex items-center gap-2 text-sm font-semibold text-emerald-700" onClick={() => navigate("/")}><ArrowLeft size={16}/>Canonical queue</button><header className="mt-6 flex flex-wrap items-start justify-between gap-5"><div><p className="eyebrow">INTERACTION REVIEW</p><h1 className="mt-2 max-w-4xl font-serif text-4xl font-semibold tracking-tight text-slate-950">{item.rawText}</h1><p className="mt-3 text-sm text-slate-500">Recorded {new Date(item.receivedAt).toLocaleString()} · {item.classifierMethod}</p></div><div className="text-right"><span className={`rounded-full px-3 py-1 text-xs font-black tracking-[.14em] ${laneColor[item.lane]}`}>{item.lane.toUpperCase()}</span><p className="mt-2 text-xs text-slate-500">Confidence {Math.round(Number(item.confidence) * 100)}% · displayed, never dispositive</p></div></header>
    <div className="mt-8 grid gap-6 xl:grid-cols-2"><article className="panel"><h2>Why this route</h2><ol className="mt-4 space-y-2 pl-5 text-sm text-slate-700">{(item.laneReasons ?? []).map((reason, index) => <li key={index}>{reason}</li>)}</ol><h3 className="mt-7 text-sm font-bold uppercase tracking-[.12em] text-slate-500">Reply gate</h3><div className={`mt-3 rounded-xl p-4 text-sm ${item.verifiedReplyStatus === "eligible" ? "bg-emerald-50 text-emerald-900" : "bg-amber-50 text-amber-950"}`}><b>{item.verifiedReplyStatus === "eligible" ? "Auto-eligible" : "Human review required"}</b><ul className="mt-2 list-disc space-y-1 pl-5">{(item.replyGateReasons ?? []).map((reason, index) => <li key={index}>{reason}</li>)}</ul></div></article><article className={`panel ${item.lane === "escalate" ? "border-rose-200 bg-rose-50/40" : ""}`}><h2>{item.lane === "escalate" ? "Decision packet" : "Prepared draft"}</h2><pre className="message mt-4 whitespace-pre-wrap">{item.draft}</pre><button className="action-primary mt-5" onClick={copy}><Copy size={15}/>{copied ? "Copied for external send" : "Copy draft for external send"}</button><p className="mt-2 text-xs text-slate-500">No Slack or email client exists in this prototype.</p></article></div>
    <div className="mt-6 grid gap-6 xl:grid-cols-[1.25fr_.75fr]"><article className="panel"><h2>Evidence and source boundary</h2><div className="mt-4 space-y-3">{evidence.map((entry, index) => <div key={index} className={`rounded-xl border p-4 text-sm ${entry.refusalCode ? "border-rose-200 bg-rose-50" : entry.advisory ? "border-amber-200 bg-amber-50" : "border-slate-200 bg-slate-50"}`}><div className="flex flex-wrap items-center gap-2"><b className="text-slate-950">{entry.label}</b>{entry.refusalCode ? <span className="badge bg-rose-100 text-rose-800"><LockKeyhole size={11}/>{entry.refusalCode}</span> : entry.advisory ? <span className="badge bg-amber-100 text-amber-900"><BadgeAlert size={11}/>AE advisory</span> : <span className="badge bg-emerald-100 text-emerald-800"><CheckCircle2 size={11}/>Citable</span>}</div><p className="mt-2 leading-6 text-slate-700">{entry.value}</p><p className="mt-2 font-mono text-[11px] text-slate-500">{entry.source}</p></div>)}</div></article><aside className="space-y-6"><article className="panel"><h2>Knowledge citations</h2>{citations.length ? <ul className="mt-4 space-y-3">{citations.map((citation, index) => <li key={`${citation.sourceId}-${citation.anchor}-${index}`}><a className="font-semibold text-emerald-700 hover:underline" href={`${citation.url}#${citation.anchor}`} target="_blank" rel="noreferrer">{citation.title} · #{citation.anchor}</a><p className="mt-1 text-xs text-slate-500">Retrieval score {Math.round(citation.score * 100)}%</p></li>)}</ul> : <p className="mt-3 text-sm text-slate-500">No attributed knowledge section was required for this interaction.</p>}</article><article className="panel"><h2>Computation audit</h2>{computations ? <pre className="mt-3 overflow-auto rounded-lg bg-slate-950 p-3 text-xs leading-5 text-emerald-100">{JSON.stringify(computations, null, 2)}</pre> : <p className="mt-3 text-sm text-slate-500">No quantitative domain computation was required.</p>}</article><article className="rounded-2xl border border-slate-200 bg-slate-950 p-5 text-slate-100"><ShieldAlert className="text-amber-300" size={20}/><h2 className="mt-3 text-sm font-bold">Disclosure control</h2><p className="mt-2 text-sm leading-6 text-slate-300">A refusal means the prototype withheld the underlying value. It is not a statement that the result is zero, absent, or safe.</p></article></aside></div></section>;
}
