import { trpc } from "@/lib/trpc";
import { AlertTriangle, ArrowRight, BadgeCheck, FlaskConical, Play, ShieldCheck } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { useLocation } from "wouter";

const users = [{ id: "northwind", label: "Priya Shah · Northwind" }, { id: "lumen", label: "Jordan Lee · Lumen" }, { id: "coman", label: "Alex Morgan · Pinecrest Co-man" }, { id: "denied", label: "Taylor Brooks · View denied" }] as const;
const classFor = (lane: string) => lane === "auto" ? "bg-emerald-100 text-emerald-800" : lane === "assisted" ? "bg-amber-100 text-amber-900" : "bg-rose-100 text-rose-800";

export default function PrototypeConsole() {
  const [, navigate] = useLocation(); const utils = trpc.useUtils();
  const bootstrap = trpc.prototype.bootstrap.useMutation({ onSuccess: () => utils.prototype.queue.invalidate() });
  const queue = trpc.prototype.queue.useQuery();
  const [userId, setUserId] = useState<(typeof users)[number]["id"]>("northwind");
  const [text, setText] = useState("quick check, where is our latest protein order sitting right now?");
  const [attachmentsPresent, setAttachmentsPresent] = useState(false);
  const run = trpc.prototype.run.useMutation({ onSuccess: result => { utils.prototype.queue.invalidate(); navigate(`/interactions/${result.interaction.id}`); } });
  useEffect(() => { bootstrap.mutate(); }, []);
  const selected = useMemo(() => users.find(user => user.id === userId), [userId]);
  return <section className="mx-auto max-w-7xl p-5 md:p-10"><header className="grid gap-7 border-b border-slate-200 pb-8 lg:grid-cols-[1.25fr_.75fr]"><div><p className="eyebrow">CANONICAL PROTOTYPE · SAFETY FIRST</p><h1 className="mt-3 max-w-3xl font-serif text-4xl font-semibold tracking-tight text-slate-950 md:text-5xl">Triage work that knows when to stop.</h1><p className="mt-4 max-w-2xl text-base leading-7 text-slate-600">The console reads the platform verdict, independently checks context, and blocks any result that is not released, permitted, or reproducible.</p></div><div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-5"><ShieldCheck className="text-emerald-700" size={22}/><h2 className="mt-4 text-sm font-bold text-emerald-950">Active safety boundary</h2><p className="mt-2 text-sm leading-6 text-emerald-900">Result visibility is enforced on the server before evidence is composed. The console records a human-copied reply; it does not send Slack or email.</p></div></header>
    <div className="mt-8 grid gap-7 xl:grid-cols-[1.1fr_.9fr]"><article className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-xl bg-slate-900 text-white"><FlaskConical size={18}/></span><div><h2 className="text-lg font-bold text-slate-950">Run an unseen message</h2><p className="text-sm text-slate-500">The same fixture-backed ingress path powers the evaluator probe.</p></div></div><form className="mt-6 space-y-4" onSubmit={event => { event.preventDefault(); run.mutate({ userId, text, attachmentsPresent }); }}><label className="field-label">Verified fixture identity</label><select className="field" value={userId} onChange={event => setUserId(event.target.value as typeof userId)}>{users.map(user => <option value={user.id} key={user.id}>{user.label}</option>)}</select><p className="-mt-2 text-xs text-slate-500">Selected: {selected?.label}. Server-side company membership and partnership checks still apply.</p><label className="field-label">Customer message</label><textarea className="field min-h-36" value={text} onChange={event => setText(event.target.value)} /><label className="flex items-center gap-2 text-sm text-slate-700"><input type="checkbox" checked={attachmentsPresent} onChange={event => setAttachmentsPresent(event.target.checked)} />Message includes specification attachment metadata</label><button className="action-primary" disabled={run.isPending}><Play size={15}/>{run.isPending ? "Assembling evidence…" : "Run canonical triage"}</button>{run.error && <p className="rounded-lg bg-rose-50 p-3 text-sm text-rose-800">{run.error.message}</p>}</form></article>
      <aside className="rounded-2xl border border-slate-200 bg-slate-950 p-6 text-slate-50"><p className="eyebrow text-emerald-300">EVALUATOR PROBES</p><h2 className="mt-3 text-xl font-semibold">Try the critical paths</h2><div className="mt-5 space-y-4 text-sm leading-6 text-slate-300"><Probe title="Auto" text="Latest protein order status" /><Probe title="Escalate" text="Lot 8812 lead result" /><Probe title="Deny" text="Hidden Bar lead result as Pinecrest" /></div><div className="mt-6 rounded-xl border border-white/10 bg-white/5 p-4 text-xs leading-5 text-slate-300"><AlertTriangle className="mb-2 text-amber-300" size={16}/>A platform verdict may be shown only with a released, permitted result. A shadow disagreement is an escalation, not an override.</div></aside></div>
    <section className="mt-8"><div className="mb-4 flex items-end justify-between gap-4"><div><p className="eyebrow">INTERACTION AUDIT</p><h2 className="mt-1 text-2xl font-semibold text-slate-950">Recent canonical runs</h2></div><button className="text-sm font-semibold text-emerald-700" onClick={() => queue.refetch()}>Refresh</button></div><div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">{queue.isLoading ? <p className="p-6 text-sm text-slate-500">Loading prototype interactions…</p> : queue.data?.length ? <div className="divide-y divide-slate-100">{queue.data.map(item => <button key={item.id} onClick={() => navigate(`/interactions/${item.id}`)} className="grid w-full grid-cols-[1fr_auto] gap-4 px-5 py-4 text-left transition hover:bg-slate-50"><div><p className="font-semibold text-slate-900">{item.rawText}</p><p className="mt-1 text-xs text-slate-500">{new Date(item.receivedAt).toLocaleString()} · {item.classifierMethod}</p></div><span className={`h-fit rounded-full px-2.5 py-1 text-[11px] font-black tracking-[.12em] ${classFor(item.lane)}`}>{item.lane.toUpperCase()} <ArrowRight className="ml-1 inline" size={12}/></span></button>)}</div> : <p className="p-6 text-sm text-slate-500">No canonical prototype interactions yet.</p>}</div></section></section>;
}

function Probe({ title, text }: { title: string; text: string }) { return <div className="border-l border-emerald-300/60 pl-3"><p className="font-bold text-emerald-200">{title}</p><p>{text}</p></div>; }
