import { ArrowDown, ArrowRight, Bot, Database, MessageSquareText, ShieldCheck } from "lucide-react";

function Flow({ icon, title, body, endpoint, tone }: { icon: React.ReactNode; title: string; body: string; endpoint: string; tone: string }) { return <div className="rounded-2xl border border-[#d6ded7] bg-white p-5"><span className={`grid h-10 w-10 place-items-center rounded-xl ${tone}`}>{icon}</span><h2 className="mt-4 font-serif text-2xl font-semibold">{title}</h2><p className="mt-2 text-sm leading-6 text-[#60766c]">{body}</p><code className="mt-4 block rounded-lg bg-[#f2f5f2] p-3 text-xs text-[#24483a]">{endpoint}</code></div> }

export default function SlackConnections() { return <section className="mx-auto max-w-6xl p-5 md:p-10"><p className="text-xs font-bold tracking-[.16em] text-[#517263]">CONNECTION MODEL</p><h1 className="mt-2 font-serif text-4xl font-semibold tracking-tight">How Slack talks to Light Labs</h1><p className="mt-3 max-w-3xl text-[#60766c]">There are two different connections. They are intentionally separate because a customer message must be captured every time, while Slackbot should query the app only when an internal teammate asks it to.</p>
  <div className="mt-8 grid gap-5 lg:grid-cols-2"><Flow icon={<MessageSquareText size={20}/>} tone="bg-[#e7f6eb] text-[#176344]" title="1. Customer message → triage queue" body="A customer or co-man sends a message in an approved Slack DM, @mention, or support channel. Slack delivers that event to Light Labs. The app verifies Slack’s signature, identifies the sender, pulls verified context, and either queues the case or uses a fully verified response template." endpoint="Slack Events API → POST /ingest"/><Flow icon={<Bot size={20}/>} tone="bg-[#e8f0fb] text-[#225e9c]" title="2. AE asks Slackbot → app data" body="An internal AE asks Slackbot a question such as “What is in my escalation queue?” Slackbot calls the Light Labs MCP server. The app verifies the signed Slack identity and returns only the AE’s permitted queue, decision packets, and cited knowledge." endpoint="Slackbot MCP → POST /mcp"/></div>
  <div className="my-8 flex flex-col items-center gap-2 text-[#80978b]"><ArrowDown/><span className="text-xs font-bold tracking-[.12em]">BOTH PATHS REQUIRE VERIFIED IDENTITY</span><ArrowDown/></div>
  <div className="grid gap-5 md:grid-cols-3"><Flow icon={<ShieldCheck size={20}/>} tone="bg-[#fff2cf] text-[#8a6300]" title="Identity bridge" body="Contact Mapping binds a customer’s Slack workspace/user to the exact Light Labs account contact and same HubSpot email record." endpoint="Slack identity + account contact + HubSpot email"/><Flow icon={<Database size={20}/>} tone="bg-[#f3eafd] text-[#6c3994]" title="CRM enrichment" body="After the bridge exists, the app may retrieve the contact, company, recent tickets, owner, and limited conversation metadata from HubSpot MCP." endpoint="Light Labs → HubSpot MCP (read-only)"/><Flow icon={<ArrowRight size={20}/>} tone="bg-[#e7f6eb] text-[#176344]" title="Safety boundary" body="If identity, evidence, retrieval relevance, or a policy gate is incomplete, the app does not answer. It opens an AE queue item instead." endpoint="Unknown or uncertain → human queue"/></div>
  <div className="panel mt-8"><h2>Turn on the two Slack connections when ready</h2><p className="mt-2 text-sm leading-6 text-[#60766c]">Nothing in Slack is required to map contacts or use HubSpot. These are the final Slack-admin steps that tell Slack where to deliver messages and Slackbot questions.</p><ol className="mt-4 grid gap-3 text-sm text-[#385249] md:grid-cols-2"><li className="rounded-lg bg-[#f7faf7] p-4"><b>1. Create one internal app.</b><br/>Create a Slack app named <b>Light Labs Triage</b>. Store its signing secret in the app’s server-side configuration; do not place it in a channel or a browser field.</li><li className="rounded-lg bg-[#f7faf7] p-4"><b>2. Enable customer-message intake.</b><br/>Under Event Subscriptions, use <code>https://lighttriage-gdngkmys.manus.space/ingest</code>. Start with only <code>app_mention</code> and <code>message.im</code>; expand to approved support channels after shadow-mode review.</li><li className="rounded-lg bg-[#f7faf7] p-4"><b>3. Add Slackbot’s MCP connection.</b><br/>In the MCP server form, enter <code>https://lighttriage-gdngkmys.manus.space/mcp</code> and select <b>Slack Identity Auth</b>. This lets Slackbot ask the app for an internal AE’s permitted queue and decision packets.</li><li className="rounded-lg bg-[#f7faf7] p-4"><b>4. Install and map before live use.</b><br/>Install the app to the intended workspace. Then use <b>Contact Mapping</b> to bind each customer’s Slack workspace/user to the same HubSpot email and Light Labs account. Unmapped senders are queued without CRM data.</li></ol><p className="mt-4 rounded-lg bg-[#fff2cf] p-3 text-xs text-[#785500]"><b>Keep the paths separate:</b> Events API is for every approved customer message. Slackbot MCP is for an internal teammate asking the bot for permitted app data. Neither path authorizes a model to send an uncertain answer.</p></div>
  </section>; }
