import { sql } from "drizzle-orm";
import { getDb } from "./db";
import { products, orders, tests, users } from "../drizzle/schema";
import { actionLimits, analyteCompanyUnits, analytes, assayCompanyPrices, assays, companies, companyMemberships, limitGroupSkuAssignments, limitGroups, partnerships, regulatoryLimits, reports, samples, shipments, skus, specifications, stabilityStudies, stabilityStudyTimePoints, testLimits, testResults, turnaroundTimes } from "../drizzle/canonicalSchema";
import { ensureKnowledgeCatalog } from "./knowledge";

const now = () => new Date(); const stamp = () => ({ createdAt: now(), updatedAt: now() });
const upsert = (db: NonNullable<Awaited<ReturnType<typeof getDb>>>, table: any, rows: any[]) => db.insert(table).values(rows).onDuplicateKeyUpdate({ set: { id: sql`values(id)` } });

export async function ensurePrototypeSeed() {
  const db = await getDb(); if (!db) throw new Error("Database unavailable");
  const existing = await db.select({ id: companies.id }).from(companies).limit(1); if (existing.length) { await ensureKnowledgeCatalog(); return; }
  const created = stamp(); const past = new Date("2026-06-01T12:00:00Z"); const newer = new Date("2026-06-10T12:00:00Z"); const future = new Date(Date.now() + 120 * 24 * 60 * 60 * 1000);
  await upsert(db, users, [
    { id: 9001, openId: "fixture-north-ops", name: "Priya Shah", firstName: "Priya", lastName: "Shah", email: "priya@northwind.demo", loginMethod: "fixture", role: "user", staffuser: 0, confirmedAt: created.createdAt, slackWorkspaceId: "T_DEMO", slackUserId: "U_NORTH_OPS", hubspotContactId: "hs_north_ops", limsId: "LIMS-U-9001", lastSignedIn: created.createdAt },
    { id: 9002, openId: "fixture-lumen-qa", name: "Jordan Lee", firstName: "Jordan", lastName: "Lee", email: "jordan@lumen.demo", loginMethod: "fixture", role: "user", staffuser: 0, confirmedAt: created.createdAt, slackWorkspaceId: "T_DEMO", slackUserId: "U_LUMEN_QA", hubspotContactId: "hs_lumen_qa", limsId: "LIMS-U-9002", lastSignedIn: created.createdAt },
    { id: 9003, openId: "fixture-coman", name: "Alex Morgan", firstName: "Alex", lastName: "Morgan", email: "alex@pinecrest.demo", loginMethod: "fixture", role: "user", staffuser: 0, confirmedAt: created.createdAt, slackWorkspaceId: "T_DEMO", slackUserId: "U_PINE_QC", hubspotContactId: "hs_pine_qc", limsId: "LIMS-U-9003", lastSignedIn: created.createdAt },
    { id: 9004, openId: "fixture-denied", name: "Taylor Brooks", firstName: "Taylor", lastName: "Brooks", email: "taylor@denied.demo", loginMethod: "fixture", role: "user", staffuser: 0, confirmedAt: created.createdAt, slackWorkspaceId: "T_DEMO", slackUserId: "U_DENIED", hubspotContactId: "hs_denied", limsId: "LIMS-U-9004", lastSignedIn: created.createdAt },
  ]);
  await upsert(db, companies, [
    { id: "co_northwind", name: "Northwind Nutrition", paymentMethod: "invoice", limsId: "LIMS-CO-001", stripeId: "cus_north", hubspotCompanyId: "hs_north", ...created }, { id: "co_lumen", name: "Lumen Foods", paymentMethod: "invoice", limsId: "LIMS-CO-002", stripeId: "cus_lumen", hubspotCompanyId: "hs_lumen", ...created }, { id: "co_pinecrest", name: "Pinecrest Manufacturing", paymentMethod: "invoice", limsId: "LIMS-CO-003", stripeId: "cus_pine", hubspotCompanyId: "hs_pine", ...created }, { id: "co_hidden", name: "Hidden Brand", paymentMethod: "credit_card", limsId: "LIMS-CO-004", stripeId: "cus_hidden", hubspotCompanyId: "hs_hidden", ...created }, { id: "co_benchmark", name: "Benchmark Research", paymentMethod: "invoice", limsId: "LIMS-CO-005", stripeId: "cus_benchmark", hubspotCompanyId: "hs_benchmark", ...created },
  ]);
  await upsert(db, companyMemberships, [
    { id: "mem_north", userId: 9001, companyId: "co_northwind", role: "supply_chain", viewResults: 1, receiveComanCoas: 0, orderPlacedNotifications: 1, ...created }, { id: "mem_lumen", userId: 9002, companyId: "co_lumen", role: "qa", viewResults: 1, receiveComanCoas: 1, orderPlacedNotifications: 1, ...created }, { id: "mem_pine", userId: 9003, companyId: "co_pinecrest", role: "coman_qc", viewResults: 1, receiveComanCoas: 1, orderPlacedNotifications: 1, ...created }, { id: "mem_denied", userId: 9004, companyId: "co_lumen", role: "viewer", viewResults: 0, receiveComanCoas: 0, orderPlacedNotifications: 0, ...created },
  ]);
  await upsert(db, partnerships, [
    { id: "part_pine_lumen", sourceCompanyId: "co_pinecrest", targetCompanyId: "co_lumen", role: "manufacturer", payer: "brand", active: 1, viewResults: 1, ...created }, { id: "part_pine_north", sourceCompanyId: "co_pinecrest", targetCompanyId: "co_northwind", role: "manufacturer", payer: "brand", active: 1, viewResults: 1, ...created }, { id: "part_pine_hidden", sourceCompanyId: "co_pinecrest", targetCompanyId: "co_hidden", role: "manufacturer", payer: "brand", active: 1, viewResults: 0, ...created },
  ]);
  await upsert(db, products, [
    { id: "prod_north_protein", accountId: "co_northwind", companyId: "co_northwind", name: "Vanilla Protein", category: "supplement", brand: "Northwind", productType: "finished_good", servingSizeG: "35", limsId: "LIMS-P-001", ...created }, { id: "prod_lumen_pouch", accountId: "co_lumen", companyId: "co_lumen", name: "Berry Toddler Pouch", category: "baby_food", brand: "Lumen", productType: "finished_good", servingSizeG: "40", limsId: "LIMS-P-002", ...created }, { id: "prod_hidden", accountId: "co_hidden", companyId: "co_hidden", name: "Hidden Bar", category: "snack", brand: "Hidden", productType: "finished_good", servingSizeG: "40", limsId: "LIMS-P-003", ...created }, { id: "prod_benchmark", accountId: "co_benchmark", companyId: "co_benchmark", name: "Benchmark Infant Pouch", category: "baby_food", brand: "Research", productType: "industry_benchmarking", servingSizeG: "40", limsId: "LIMS-P-004", ...created },
  ]);
  await upsert(db, skus, [
    { id: "sku_north_protein", name: "Vanilla Protein 1kg", code: "NORTH-VAN-1", productId: "prod_north_protein", servingSizeGrams: "35", servingSizeUnit: "g", specRequiresServingSize: 0, limsId: "LIMS-SKU-001", ...created }, { id: "sku_lumen_pouch", name: "Berry Toddler Pouch", code: "LUMEN-BERRY", productId: "prod_lumen_pouch", servingSizeGrams: "40", servingSizeUnit: "g", specRequiresServingSize: 1, limsId: "LIMS-SKU-002", ...created }, { id: "sku_hidden", name: "Hidden Bar", code: "HIDDEN-BAR", productId: "prod_hidden", servingSizeGrams: "40", servingSizeUnit: "g", specRequiresServingSize: 1, limsId: "LIMS-SKU-003", ...created }, { id: "sku_benchmark", name: "Benchmark Infant Pouch", code: "BENCH-INFANT", productId: "prod_benchmark", servingSizeGrams: "40", servingSizeUnit: "g", specRequiresServingSize: 1, limsId: "LIMS-SKU-004", ...created },
  ]);
  await upsert(db, orders, [
    { id: "ord_north_latest", accountId: "co_northwind", companyId: "co_northwind", placedAt: newer, orderedAt: newer, status: "created", paymentStatus: "paid", purchaseOrderNumber: "PO-NORTH-22", limsId: "LIMS-O-001", ...created }, { id: "ord_lumen", accountId: "co_lumen", companyId: "co_lumen", placedAt: past, orderedAt: past, status: "completed", paymentStatus: "paid", purchaseOrderNumber: "PO-LUMEN-18", limsId: "LIMS-O-002", ...created }, { id: "ord_hidden", accountId: "co_hidden", companyId: "co_hidden", placedAt: past, orderedAt: past, status: "completed", paymentStatus: "paid", purchaseOrderNumber: "PO-HIDDEN-09", limsId: "LIMS-O-003", ...created },
  ]);
  await upsert(db, shipments, [{ id: "ship_north", companyId: "co_northwind", status: "in_transit", carrier: "FedEx", trackingNumber: "NORTH-TRACK-9", estimatedDeliveryDate: future, inTransitAt: newer, limsId: "LIMS-SH-001", ...created }]);
  await upsert(db, samples, [
    { id: "sample_lumen_8812", name: "Lumen 8812", orderId: "ord_lumen", skuId: "sku_lumen_pouch", lot: "8812", batch: "B-8812", shipmentId: null, composite: 0, timeOfCollection: past, servingSizeGrams: "40", servingSizeUnit: "g", labReportedServingSize: "45", labReportedServingSizeUnit: "g", limsId: "LIMS-S-8812", ...created }, { id: "sample_lumen_8709", name: "Lumen 8709", orderId: "ord_lumen", skuId: "sku_lumen_pouch", lot: "LOT-8812", batch: "B-8709", composite: 0, timeOfCollection: new Date("2026-05-01T12:00:00Z"), servingSizeGrams: "40", servingSizeUnit: "g", labReportedServingSize: "40", labReportedServingSizeUnit: "g", limsId: "LIMS-S-8709", ...created }, { id: "sample_lumen_8654", name: "Lumen 8654", orderId: "ord_lumen", skuId: "sku_lumen_pouch", lot: "8812-A", batch: "B-8654", composite: 0, timeOfCollection: new Date("2026-04-01T12:00:00Z"), servingSizeGrams: "40", servingSizeUnit: "g", labReportedServingSize: "40", labReportedServingSizeUnit: "g", limsId: "LIMS-S-8654", ...created }, { id: "sample_lumen_8590", name: "Lumen 8590", orderId: "ord_lumen", skuId: "sku_lumen_pouch", lot: "08812", batch: "B-8590", composite: 0, timeOfCollection: new Date("2026-03-01T12:00:00Z"), servingSizeGrams: "40", servingSizeUnit: "g", labReportedServingSize: "40", labReportedServingSizeUnit: "g", limsId: "LIMS-S-8590", ...created }, { id: "sample_hidden", name: "Hidden sample", orderId: "ord_hidden", skuId: "sku_hidden", lot: "H-1", batch: "H-1", composite: 0, timeOfCollection: past, servingSizeGrams: "40", servingSizeUnit: "g", labReportedServingSize: "40", labReportedServingSizeUnit: "g", limsId: "LIMS-S-H1", ...created },
  ]);
  await upsert(db, analytes, [{ id: "an_lead", name: "lead", shortName: "Pb", categoryId: "heavy_metals", limsId: "LIMS-A-PB", ...created }, { id: "an_d3", name: "vitamin_d3", shortName: "D3", categoryId: "vitamins", limsId: "LIMS-A-D3", ...created }]);
  await upsert(db, analyteCompanyUnits, [{ id: "acu_lumen_lead", analyteId: "an_lead", companyId: "co_lumen", platformUnit: "ppb", coaUnit: "ug/serving", pipUnit: "ppm", ...created }]);
  await upsert(db, assays, [{ id: "assay_metals", name: "Heavy Metals Panel", method: "ICP-MS", methodDescription: "Multi-element ICP-MS panel", price: "450", accredited: 1, forProp65: 1, forAb899: 1, purchasable: 1, minimumSampleSizeGrams: "10", averageTurnaroundTimeHours: 120, turnaroundTimeLabel: "5 business days", limsId: "LIMS-ASSAY-01", ...created }, { id: "assay_d3", name: "Vitamin D3 Potency", method: "HPLC", methodDescription: "Vitamin potency by HPLC", price: "275", accredited: 1, forProp65: 0, forAb899: 0, purchasable: 1, minimumSampleSizeGrams: "5", averageTurnaroundTimeHours: 96, turnaroundTimeLabel: "4 business days", limsId: "LIMS-ASSAY-02", ...created }]);
  await upsert(db, assayCompanyPrices, [{ id: "acp_lumen_metals", assayId: "assay_metals", companyId: "co_lumen", price: "425", ...created }, { id: "acp_north_metals", assayId: "assay_metals", companyId: "co_northwind", price: "410", ...created }]);
  await upsert(db, turnaroundTimes, [{ id: "tat_metals_rush", assayId: "assay_metals", days: 3, fee: "150", feeType: "rush", ...created }]);
  await upsert(db, tests, [
    { id: "test_north_order", orderId: "ord_north_latest", assay: "Heavy Metals Panel", status: "in_progress", sampleId: null, assayId: "assay_metals", qbenchState: "In Progress", specStatus: "no_spec", estimatedCompleteDate: future, publishedAt: null, limsId: "LIMS-T-NORTH", createdAt: past, updatedAt: newer }, { id: "test_lumen_8812", orderId: "ord_lumen", assay: "Heavy Metals Panel", status: "completed", sampleId: "sample_lumen_8812", assayId: "assay_metals", qbenchState: "Flagged", specStatus: "in_spec", completeDate: newer, publishedAt: newer, laboratoryNotes: "Serving size verification required.", limsId: "LIMS-T-8812", createdAt: past, updatedAt: newer }, { id: "test_lumen_8709", orderId: "ord_lumen", assay: "Heavy Metals Panel", status: "completed", sampleId: "sample_lumen_8709", assayId: "assay_metals", qbenchState: "Released", specStatus: "in_spec", completeDate: newer, publishedAt: newer, limsId: "LIMS-T-8709", createdAt: past, updatedAt: newer }, { id: "test_hidden", orderId: "ord_hidden", assay: "Heavy Metals Panel", status: "completed", sampleId: "sample_hidden", assayId: "assay_metals", qbenchState: "Released", specStatus: "in_spec", completeDate: newer, publishedAt: newer, limsId: "LIMS-T-HIDDEN", createdAt: past, updatedAt: newer },
  ]);
  await upsert(db, testResults, [{ id: "tr_lumen_8812", testId: "test_lumen_8812", analyteId: "an_lead", concentration: "12.4", unit: "ppb", lod: "0.1", loq: "0.1", evaluation: "detected", limsId: "LIMS-R-8812", ...created }, { id: "tr_lumen_8709", testId: "test_lumen_8709", analyteId: "an_lead", concentration: "6.2", unit: "ppb", lod: "0.1", loq: "0.1", evaluation: "detected", limsId: "LIMS-R-8709", ...created }, { id: "tr_hidden", testId: "test_hidden", analyteId: "an_lead", concentration: "5.1", unit: "ppb", lod: "0.1", loq: "0.1", evaluation: "detected", limsId: "LIMS-R-HIDDEN", ...created }]);
  await upsert(db, testLimits, [{ id: "tl_lumen_8812", testId: "test_lumen_8812", analyteId: "an_lead", customized: 1, source: "Lumen applied test snapshot", limitType: "upper", limitUnit: "ug/serving", limitBasis: "per_serving", upperBound: "0.5", lowerBound: null, limsId: "LIMS-TL-8812", createdAt: past, updatedAt: past }, { id: "tl_lumen_8709", testId: "test_lumen_8709", analyteId: "an_lead", customized: 1, source: "Lumen applied test snapshot", limitType: "upper", limitUnit: "ug/serving", limitBasis: "per_serving", upperBound: "0.5", lowerBound: null, limsId: "LIMS-TL-8709", createdAt: past, updatedAt: past }, { id: "tl_hidden", testId: "test_hidden", analyteId: "an_lead", customized: 1, source: "Hidden applied test snapshot", limitType: "upper", limitUnit: "ug/serving", limitBasis: "per_serving", upperBound: "0.5", lowerBound: null, limsId: "LIMS-TL-HIDDEN", createdAt: past, updatedAt: past }]);
  await upsert(db, specifications, [{ id: "spec_lumen_current", skuId: "sku_lumen_pouch", analyteId: "an_lead", source: "Lumen current specification", limitType: "upper", limitUnit: "ug/serving", limitBasis: "per_serving", upperBound: "0.45", lowerBound: null, ...created }]);
  await upsert(db, actionLimits, [{ id: "al_lumen_lead", skuId: "sku_lumen_pouch", analyteId: "an_lead", limitType: "upper", limitUnit: "ppb", limitBasis: "per_kg", upperBound: "20", lowerBound: null, ...created }]);
  await upsert(db, limitGroups, [{ id: "lg_lumen", name: "Lumen toddler default", source: "Lumen template", limsId: "LIMS-LG-01", ...created }]); await upsert(db, limitGroupSkuAssignments, [{ id: "lgsa_lumen", limitGroupId: "lg_lumen", skuId: "sku_lumen_pouch", missingServingSize: 1, ...created }]);
  await upsert(db, regulatoryLimits, [{ id: "rl_prop65_lead", name: "Prop 65", analyteId: "an_lead", citation: "Approved knowledge anchor required", limitType: "upper", limitUnit: "ug/serving", limitBasis: "per_serving", upperBound: "0.5", lowerBound: null, ...created }, { id: "rl_ab899_lead", name: "AB 899", analyteId: "an_lead", citation: "Approved knowledge anchor required", limitType: "upper", limitUnit: "ppb", limitBasis: "per_kg", upperBound: "5", lowerBound: null, ...created }]);
  await upsert(db, reports, [{ id: "report_lumen", testId: "test_lumen_8812", state: "published", attachedTo: "test", isPublic: 1, dateGenerated: newer, datePublished: newer, renderStatus: "ready", limsId: "LIMS-REPORT-01", ...created }, { id: "report_hidden", testId: "test_hidden", state: "published", attachedTo: "test", isPublic: 1, dateGenerated: newer, datePublished: newer, renderStatus: "ready", limsId: "LIMS-REPORT-02", ...created }]);
  await upsert(db, stabilityStudies, [{ id: "study_lumen", name: "Lumen pouch stability", companyId: "co_lumen", skuId: "sku_lumen_pouch", arm: "ambient", requiredUnits: 2, ...created }]); await upsert(db, stabilityStudyTimePoints, [{ id: "tp_lumen_6", stabilityStudyId: "study_lumen", monthOffset: 6, date: future, ...created }]);
  await ensureKnowledgeCatalog();
}
