import { and, asc, desc, eq, gte, inArray, isNotNull, sql } from "drizzle-orm";
import { nanoid } from "nanoid";
import { invokeLLM } from "./_core/llm";
import { getDb } from "./db";
import { accounts, clarifications, contacts, hubspotContextSnapshots, interactions, kbEntries, lots, orders, products, responseFeedback, results, specs, teamMembers, tests } from "../drizzle/schema";
import { ensureKnowledgeCatalog } from "./knowledge";

export type Lane = "auto" | "assisted" | "escalate";
export type Intent = "ORDER_STATUS" | "OOS_RESULT" | "SPEC_INTAKE" | "TEST_RECOMMENDATION" | "OPS_SHIPPING" | "LABEL_CLAIM_VARIANCE" | "ASSAY_SCOPE_QUESTION" | "PRICING_QUOTE" | "HUMAN_ESCALATION_REQUEST" | "OPS_DATA_EXPORT" | "UNKNOWN";
type Fixture = { id: number; source: "slack" | "email"; text: string; accountId: string; contactId: string; classification: { intents: Intent[]; confidence: number; imminent?: boolean; lotId?: string; productId?: string; analyte?: string } };
const NOW = () => new Date();
const futureOrder = () => new Date(Date.now() + 21 * 24 * 60 * 60 * 1000);
const severity: Record<Lane, number> = { escalate: 0, assisted: 1, auto: 2 };
const tier = (spend: number) => spend >= 500000 ? "T1" : spend >= 100000 ? "T2" : "T3";

export const APPENDIX_A: Fixture[] = [
  { id: 1, source: "slack", text: "hey any update on the vanilla protein order from last week? our retailer needs the COA by thursday", accountId: "acct_northwind", contactId: "con_northwind_ops", classification: { intents: ["ORDER_STATUS"], confidence: .96, productId: "prod_vanilla" } },
  { id: 2, source: "slack", text: "lot 8812 came back at 12.4 ppb lead, our spec is 10. last 3 lots of the same product were all under 7. before we quarantine and notify the brand, can you confirm this isn't a lab issue? need an answer today", accountId: "acct_lumen", contactId: "con_lumen_qa", classification: { intents: ["OOS_RESULT"], confidence: .97, imminent: true, lotId: "lot_8812", productId: "prod_berry", analyte: "lead" } },
  { id: 3, source: "email", text: "Attaching specs for our 4 new SKUs (see spreadsheet). Can you get these set up in the platform and let me know what tests you'd recommend for a California launch?", accountId: "acct_harborline", contactId: "con_harborline_qa", classification: { intents: ["SPEC_INTAKE", "TEST_RECOMMENDATION"], confidence: .93 } },
  { id: 4, source: "slack", text: "can you resend shipping labels for the 6 samples going out tomorrow? also the FedEx pickup didn't happen yesterday", accountId: "acct_pinecrest", contactId: "con_pine_qc", classification: { intents: ["OPS_SHIPPING"], confidence: .95 } },
  { id: 5, source: "email", text: "Our Vitamin D3 result says 890 IU but our label claims 1000 IU per serving. Is this a fail? Do we need to reformulate or is this within acceptable overage/variance?", accountId: "acct_verdant", contactId: "con_verdant_qa", classification: { intents: ["LABEL_CLAIM_VARIANCE"], confidence: .94, productId: "prod_d3", analyte: "vitamin_d3" } },
  { id: 6, source: "slack", text: "what's the difference between the micro panel you quoted and the one our old lab ran? prices are pretty different", accountId: "acct_summit", contactId: "con_summit_owner", classification: { intents: ["ASSAY_SCOPE_QUESTION", "PRICING_QUOTE"], confidence: .91 } },
  { id: 7, source: "slack", text: "[customer] is threatening to pull the product over the cadmium result. can you get someone from the lab on a call monday morning", accountId: "acct_pinecrest", contactId: "con_pine_qc", classification: { intents: ["HUMAN_ESCALATION_REQUEST", "OOS_RESULT"], confidence: .89, imminent: true, lotId: "lot_cb_17", productId: "prod_cacao", analyte: "cadmium" } },
  { id: 8, source: "email", text: "Can you send me everything we've tested this year? Our new QA hire is starting and wants to review history.", accountId: "acct_riverstone", contactId: "con_riverstone_qa", classification: { intents: ["OPS_DATA_EXPORT"], confidence: .96 } },
];

const seed = async () => {
  const db = await getDb(); if (!db) throw new Error("Database unavailable");
  const existing = await db.select({ id: accounts.id }).from(accounts).limit(1); if (existing.length) { await supplementalSeed(db); return; }
  await db.insert(teamMembers).values([{ id: "usr_sarah", name: "Sarah Chen", email: "sarah@lightlabs.demo", role: "ae" }, { id: "usr_marcus", name: "Marcus Reid", email: "marcus@lightlabs.demo", role: "ae" }, { id: "usr_elena", name: "Dr. Elena Vasquez", email: "elena@lightlabs.demo", role: "lab_director" }, { id: "usr_admin", name: "Demo Admin", email: "admin@lightlabs.demo", role: "admin" }]);
  await db.insert(accounts).values([{ id: "acct_pinecrest", name: "Pinecrest Manufacturing", accountType: "coman", annualSpend: 840000, slackChannel: "#lightlabs-pinecrest", ownerId: "usr_sarah" }, { id: "acct_lumen", name: "Lumen Foods", accountType: "brand", annualSpend: 156000, slackChannel: "#lightlabs-lumen", ownerId: "usr_sarah" }, { id: "acct_northwind", name: "Northwind Nutrition", accountType: "brand", annualSpend: 92000, slackChannel: "#lightlabs-northwind", ownerId: "usr_sarah" }, { id: "acct_harborline", name: "Harborline Foods", accountType: "brand", annualSpend: 118000, slackChannel: "#lightlabs-harborline", ownerId: "usr_marcus" }, { id: "acct_verdant", name: "Verdant Wellness", accountType: "brand", annualSpend: 210000, slackChannel: "#lightlabs-verdant", ownerId: "usr_marcus" }, { id: "acct_summit", name: "Summit Nutrition", accountType: "brand", annualSpend: 78000, slackChannel: "#lightlabs-summit", ownerId: "usr_marcus" }, { id: "acct_riverstone", name: "Riverstone Organics", accountType: "brand", annualSpend: 128000, slackChannel: "#lightlabs-riverstone", ownerId: "usr_sarah" }]);
  await db.insert(contacts).values([{ id: "con_pine_qc", accountId: "acct_pinecrest", name: "Alex Morgan", email: "alex@pinecrest.demo", slackUserId: "U_PINE_QC", slackWorkspaceId: "T_DEMO", hubspotPortalId: "demo_portal", hubspotContactId: "hs_pine_qc", identityStatus: "verified", verifiedAt: NOW(), roleTitle: "QC Manager", hasPlatformLogin: 1 }, { id: "con_northwind_ops", accountId: "acct_northwind", name: "Priya Shah", email: "priya@northwind.demo", slackUserId: "U_NORTH_OPS", slackWorkspaceId: "T_DEMO", hubspotPortalId: "demo_portal", hubspotContactId: "hs_north_ops", identityStatus: "verified", verifiedAt: NOW(), roleTitle: "Supply Chain Lead", hasPlatformLogin: 0 }, { id: "con_lumen_qa", accountId: "acct_lumen", name: "Jordan Lee", email: "jordan@lumen.demo", slackUserId: "U_LUMEN_QA", slackWorkspaceId: "T_DEMO", hubspotPortalId: "demo_portal", hubspotContactId: "hs_lumen_qa", identityStatus: "verified", verifiedAt: NOW(), roleTitle: "QA Manager", hasPlatformLogin: 1 }, { id: "con_verdant_qa", accountId: "acct_verdant", name: "Taylor Brooks", email: "taylor@verdant.demo", slackUserId: "U_VERDANT_QA", slackWorkspaceId: "T_DEMO", hubspotPortalId: "demo_portal", hubspotContactId: "hs_verdant_qa", identityStatus: "verified", verifiedAt: NOW(), roleTitle: "Quality Director", hasPlatformLogin: 1 }, { id: "con_harborline_qa", accountId: "acct_harborline", name: "Casey Nguyen", email: "casey@harborline.demo", slackUserId: "U_HARBOR_QA", slackWorkspaceId: "T_DEMO", hubspotPortalId: "demo_portal", hubspotContactId: "hs_harbor_qa", identityStatus: "verified", verifiedAt: NOW(), roleTitle: "QA Manager", hasPlatformLogin: 1 }, { id: "con_summit_owner", accountId: "acct_summit", name: "Mika Patel", email: "mika@summit.demo", slackUserId: "U_SUMMIT_OWNER", slackWorkspaceId: "T_DEMO", hubspotPortalId: "demo_portal", hubspotContactId: "hs_summit_owner", identityStatus: "verified", verifiedAt: NOW(), roleTitle: "Founder", hasPlatformLogin: 0 }, { id: "con_riverstone_qa", accountId: "acct_riverstone", name: "Avery Kim", email: "avery@riverstone.demo", slackUserId: "U_RIVER_QA", slackWorkspaceId: "T_DEMO", hubspotPortalId: "demo_portal", hubspotContactId: "hs_river_qa", identityStatus: "verified", verifiedAt: NOW(), roleTitle: "Quality Manager", hasPlatformLogin: 1 }]);
  await db.insert(products).values([{ id: "prod_vanilla", accountId: "acct_northwind", name: "Vanilla Protein", category: "protein", servingSizeG: "35" }, { id: "prod_berry", accountId: "acct_lumen", name: "Berry Toddler Pouch", category: "toddler_food", servingSizeG: "99" }, { id: "prod_d3", accountId: "acct_verdant", name: "Vitamin D3 Softgel", category: "supplement", servingSizeG: "1" }, { id: "prod_cacao", accountId: "acct_pinecrest", name: "Cacao Bar", category: "snack", servingSizeG: "40" }]);
  await db.insert(lots).values([{ id: "lot_8812", productId: "prod_berry", comanId: "acct_pinecrest", producedAt: NOW() }, { id: "lot_cb_17", productId: "prod_cacao", comanId: "acct_pinecrest", producedAt: NOW() }]);
  await db.insert(orders).values([{ id: "ord_4721", accountId: "acct_northwind", placedAt: NOW(), promisedAt: futureOrder(), status: "on_instrument", queuePosition: 3, assayGroup: "ICP-MS" }, { id: "ord_4650", accountId: "acct_lumen", placedAt: new Date("2025-01-01"), promisedAt: new Date("2025-01-05"), status: "delayed", queuePosition: 1, assayGroup: "ICP-MS" }]);
  await db.insert(tests).values([{ id: "test_8812", orderId: "ord_4650", lotId: "lot_8812", assay: "ICP-MS heavy metals", status: "completed", completedAt: NOW() }, { id: "test_d3", lotId: "lot_d3", assay: "Vitamin D", status: "completed", completedAt: NOW() }]);
  await db.insert(results).values([{ id: "res_lead", testId: "test_8812", analyte: "lead", value: "12.4", unit: "ppb", isNonDetect: 0, loq: "0.1", reportedAt: NOW() }, { id: "res_d3", testId: "test_d3", analyte: "vitamin_d3", value: "890", unit: "IU", isNonDetect: 0, loq: "10", reportedAt: NOW() }]);
  await db.insert(specs).values([{ id: "spec_lumen_lead", scope: "account", scopeId: "acct_lumen", analyte: "lead", limitValue: "10", limitUnit: "ppb", source: "Lumen Foods supplier spec v4", citation: "effective 2026-01-01", isPlaceholder: 0 }, { id: "spec_prop65", scope: "regulatory", category: "toddler_food", analyte: "lead", limitValue: "0.5", limitUnit: "ug/serving", source: "PROP65 CA", citation: "PLACEHOLDER — not verified", isPlaceholder: 1 }, { id: "spec_fda", scope: "regulatory", category: "toddler_food", analyte: "lead", limitValue: "10", limitUnit: "ppb", source: "FDA US", citation: "PLACEHOLDER — not verified", isPlaceholder: 1 }]);
  await db.insert(kbEntries).values([{ id: "kb_oos", questionPattern: "out of spec lab issue", answer: "Confirm run QC, stated method uncertainty, sample handling, and matching specification basis before asserting whether a result is a lab issue.", author: "Dr. Elena Vasquez", approvedBy: "Vijay Manohar", createdAt: NOW() }]);
  await supplementalSeed(db);
};

async function supplementalSeed(db: NonNullable<Awaited<ReturnType<typeof getDb>>>) {
  const upsert = <T extends { id: string }>(table: any, values: T[]) => db.insert(table).values(values as any).onDuplicateKeyUpdate({ set: { id: sql`values(id)` } });
  await db.insert(teamMembers).values([{ id: "usr_sarah", name: "Sarah Chen", email: "sarah@lightlabs.demo", role: "ae", slackUserId: "U_AE_SARAH", slackWorkspaceId: "T_DEMO" }, { id: "usr_marcus", name: "Marcus Reid", email: "marcus@lightlabs.demo", role: "ae", slackUserId: "U_AE_MARCUS", slackWorkspaceId: "T_DEMO" }, { id: "usr_elena", name: "Dr. Elena Vasquez", email: "elena@lightlabs.demo", role: "lab_director", slackUserId: "U_LAB_ELENA", slackWorkspaceId: "T_DEMO" }, { id: "usr_admin", name: "Demo Admin", email: "admin@lightlabs.demo", role: "admin", slackUserId: "U_ADMIN", slackWorkspaceId: "T_DEMO" }]).onDuplicateKeyUpdate({ set: { slackUserId: sql`values(slack_user_id)`, slackWorkspaceId: sql`values(slack_workspace_id)` } });
  await upsert(products, [
    { id: "prod_harborline", accountId: "acct_harborline", name: "California Launch SKU", category: "supplement", servingSizeG: "30" },
    { id: "prod_harborline_2", accountId: "acct_harborline", name: "California Launch SKU 2", category: "supplement", servingSizeG: "28" },
    { id: "prod_harborline_3", accountId: "acct_harborline", name: "California Launch SKU 3", category: "supplement", servingSizeG: "32" },
    { id: "prod_harborline_4", accountId: "acct_harborline", name: "California Launch SKU 4", category: "supplement", servingSizeG: "25" },
    { id: "prod_pine_samples", accountId: "acct_pinecrest", name: "Six-sample outbound set", category: "contract_manufacturing", servingSizeG: null },
    { id: "prod_summit_micro", accountId: "acct_summit", name: "Micro Panel Quote", category: "supplement", servingSizeG: "12" },
    { id: "prod_river_green", accountId: "acct_riverstone", name: "Greens Blend", category: "supplement", servingSizeG: "10" },
  ]);
  await upsert(lots, [
    { id: "lot_d3", productId: "prod_d3", comanId: null, producedAt: NOW() },
    { id: "lot_8709", productId: "prod_berry", comanId: "acct_pinecrest", producedAt: new Date("2026-06-30") },
    { id: "lot_8654", productId: "prod_berry", comanId: "acct_pinecrest", producedAt: new Date("2026-06-02") },
    { id: "lot_8590", productId: "prod_berry", comanId: "acct_pinecrest", producedAt: new Date("2026-05-05") },
  ]);
  await upsert(orders, [
    { id: "ord_ship_pine", accountId: "acct_pinecrest", placedAt: NOW(), promisedAt: futureOrder(), status: "pickup_exception", queuePosition: 1, assayGroup: "shipping" },
    { id: "ord_export_river", accountId: "acct_riverstone", placedAt: NOW(), promisedAt: null, status: "released", queuePosition: null, assayGroup: "history_export" },
  ]);
  await upsert(tests, [
    { id: "test_8709", orderId: null, lotId: "lot_8709", assay: "ICP-MS heavy metals", status: "completed", completedAt: NOW() },
    { id: "test_8654", orderId: null, lotId: "lot_8654", assay: "ICP-MS heavy metals", status: "completed", completedAt: NOW() },
    { id: "test_8590", orderId: null, lotId: "lot_8590", assay: "ICP-MS heavy metals", status: "completed", completedAt: NOW() },
    { id: "test_cb17", orderId: "ord_ship_pine", lotId: "lot_cb_17", assay: "ICP-MS heavy metals", status: "completed", completedAt: NOW() },
  ]);
  await upsert(results, [
    { id: "res_8709", testId: "test_8709", analyte: "lead", value: "6.2", unit: "ppb", isNonDetect: 0, loq: "0.1", reportedAt: NOW() },
    { id: "res_8654", testId: "test_8654", analyte: "lead", value: "5.8", unit: "ppb", isNonDetect: 0, loq: "0.1", reportedAt: NOW() },
    { id: "res_8590", testId: "test_8590", analyte: "lead", value: "6.9", unit: "ppb", isNonDetect: 0, loq: "0.1", reportedAt: NOW() },
    { id: "res_cadmium_cb17", testId: "test_cb17", analyte: "cadmium", value: "2.8", unit: "ppb", isNonDetect: 0, loq: "0.1", reportedAt: NOW() },
  ]);
  await upsert(specs, [
    { id: "spec_harborline_launch", scope: "account", scopeId: "acct_harborline", category: "supplement", analyte: "micro_panel", limitValue: null, limitUnit: null, source: "Harborline launch specification", citation: "Pending customer upload", isPlaceholder: 0 },
    { id: "spec_summit_quote", scope: "account", scopeId: "acct_summit", category: "supplement", analyte: "micro_panel", limitValue: null, limitUnit: null, source: "Light Labs micro panel quote", citation: "Scope document on file", isPlaceholder: 0 },
    { id: "spec_summit_old_lab", scope: "account", scopeId: "acct_summit", category: "supplement", analyte: "micro_panel", limitValue: null, limitUnit: null, source: "Prior laboratory panel", citation: "Customer-provided scope comparison pending review", isPlaceholder: 0 },
  ]);
}

const baseLane = (intents: Intent[]): Lane => {
  if (intents.some(i => ["LABEL_CLAIM_VARIANCE", "TEST_RECOMMENDATION", "HUMAN_ESCALATION_REQUEST", "UNKNOWN"].includes(i))) return "escalate";
  if (intents.some(i => ["OOS_RESULT", "SPEC_INTAKE", "ASSAY_SCOPE_QUESTION", "PRICING_QUOTE"].includes(i))) return "assisted";
  return "auto";
};
const standardEvidence = (classification: { intents: Intent[]; lotId?: string; analyte?: string }, accountName?: string) => {
  const items: Array<{ label: string; value: string; source: string; citable: boolean }> = [{ label: "Account", value: accountName ?? "Unidentified sender", source: "contacts + accounts", citable: true }];
  if (classification.lotId === "lot_8812") items.push({ label: "Lead result", value: "12.4 ppb against customer internal spec of 10 ppb — exceeds by 24%.", source: "results + specs", citable: true }, { label: "Regulatory reference", value: "PROP65 CA limit placeholder shown for routing only; it cannot be quoted.", source: "regulatory registry placeholder", citable: false });
  if (classification.intents.includes("LABEL_CLAIM_VARIANCE")) items.push({ label: "Serving-size basis", value: "Product has a reformulation history; a percentage comparison is not safe until the serving-size basis is verified.", source: "products + formulation history", citable: true });
  if (classification.intents.includes("ORDER_STATUS")) items.push({ label: "Order ord_4721", value: "On instrument, position 3 in the ICP-MS queue; promised within the current demo window.", source: "orders", citable: true });
  return items;
};
const compose = (lane: Lane, intents: Intent[], accountName?: string) => {
  if (lane === "auto" && intents.includes("ORDER_STATUS")) return { acknowledgment: "I’ve checked the order: it is on instrument, position 3 in the ICP-MS queue. I’ll keep the COA moving before the retailer deadline.", draft: "Your vanilla protein order is on instrument and third in the ICP-MS queue. We are tracking it against the committed COA timing." };
  if (lane === "auto") return { acknowledgment: "Received — the operational request is being prepared now.", draft: "Your operational request is ready for completion. We are also reviewing the missed-pickup signal internally." };
  if (lane === "assisted") return { acknowledgment: "Received. I’m assembling the relevant records and will respond with a reviewed comparison shortly.", draft: "Draft for AE review: I’ve assembled the available scope and quote records. I will avoid characterizing an outside laboratory’s panel until we have its documented scope." };
  return { acknowledgment: "Received. I’ve routed this to the appropriate lab and account team for a reviewed response.", draft: "DECISION REQUIRED — not a customer-ready answer. Confirm evidence, method basis, and accountable lab owner before communicating any scientific, regulatory, or inventory-impacting conclusion." };
};

function verifiedReplyGate(input: { contact: typeof contacts.$inferSelect | undefined; account: typeof accounts.$inferSelect | undefined; lane: Lane; evidence: Array<{ citable: boolean }>; injected: boolean; classification: { intents: Intent[]; productId?: string } }) {
  const reasons: string[] = [];
  if (!input.contact || !input.account) reasons.push("A verified sender-to-account identity is required.");
  if (input.lane !== "auto") reasons.push("This interaction is not in an auto-eligible operational lane.");
  if (input.evidence.some(item => !item.citable)) reasons.push("All customer-facing evidence must be citable.");
  if (!input.injected) reasons.push("No deterministic entity-resolution record is available for this live interaction.");
  if (!input.classification.intents.includes("ORDER_STATUS")) reasons.push("No approved verified-response template exists for this intent.");
  if (!input.classification.productId) reasons.push("The referenced product was not deterministically resolved.");
  return { status: reasons.length ? "ineligible" as const : "eligible" as const, reasons };
}

async function classify(text: string, context: string): Promise<{ intents: Intent[]; confidence: number; imminent?: boolean }> {
  const schema = { type: "object", properties: { intents: { type: "array", items: { type: "string", enum: ["ORDER_STATUS","OOS_RESULT","SPEC_INTAKE","TEST_RECOMMENDATION","OPS_SHIPPING","LABEL_CLAIM_VARIANCE","ASSAY_SCOPE_QUESTION","PRICING_QUOTE","HUMAN_ESCALATION_REQUEST","OPS_DATA_EXPORT","UNKNOWN"] }, minItems: 1 }, confidence: { type: "number", minimum: 0, maximum: 1 }, imminent: { type: "boolean" } }, required: ["intents","confidence","imminent"], additionalProperties: false };
  const llm = invokeLLM({ model: "gpt-5-mini", messages: [{ role: "system", content: "Classify the customer interaction using only the allowed intent enum. Return UNKNOWN if the information is insufficient. Never provide a scientific, regulatory, or customer-facing answer." }, { role: "user", content: `Verified context: ${context}\n\nInteraction: ${text}` }], response_format: { type: "json_schema", json_schema: { name: "triage_classification", strict: true, schema } } });
  try { const response = await Promise.race([llm, new Promise<never>((_, reject) => setTimeout(() => reject(new Error("classifier_timeout")), 1200))]); const content = response.choices[0]?.message?.content; const parsed = typeof content === "string" ? JSON.parse(content) : null; if (!parsed || !Array.isArray(parsed.intents)) throw new Error("invalid_classifier_output"); return { intents: parsed.intents as Intent[], confidence: Number(parsed.confidence) || 0, imminent: Boolean(parsed.imminent) }; } catch { return { intents: ["UNKNOWN"], confidence: 0 }; }
}

export async function ensureDemoData() { await seed(); await ensureKnowledgeCatalog(); }
export async function runTriage(input: { source: string; channelRef: string | null; rawText: string; slackUserId?: string | null; slackWorkspaceId?: string | null; injected?: Fixture["classification"] }) {
  await seed(); const db = await getDb(); if (!db) throw new Error("Database unavailable"); const started = Date.now();
  if (input.channelRef) { const duplicate = await db.select().from(interactions).where(and(eq(interactions.source, input.source), eq(interactions.channelRef, input.channelRef))).limit(1); if (duplicate[0]) return { duplicate: true, interaction: duplicate[0] }; }
  const contact = input.slackUserId && input.slackWorkspaceId ? (await db.select().from(contacts).where(and(eq(contacts.slackUserId, input.slackUserId), eq(contacts.slackWorkspaceId, input.slackWorkspaceId), eq(contacts.identityStatus, "verified"), isNotNull(contacts.email))).limit(1))[0] : undefined;
  const account = contact ? (await db.select().from(accounts).where(eq(accounts.id, contact.accountId)).limit(1))[0] : undefined;
  const crmSnapshot = !input.injected && contact?.hubspotContactId && /^\d+$/.test(contact.hubspotContactId) ? (await db.select().from(hubspotContextSnapshots).where(and(eq(hubspotContextSnapshots.contactId, contact.id), eq(hubspotContextSnapshots.status, "available"), gte(hubspotContextSnapshots.retrievedAt, new Date(Date.now() - 15 * 60 * 1000)))).orderBy(desc(hubspotContextSnapshots.retrievedAt)).limit(1))[0] : undefined;
  const inferred = input.injected ?? await classify(input.rawText, account ? `${account.name}; tier ${tier(account.annualSpend)}; no account data may be invented.` : "Unidentified sender. Do not expose account data.");
  let lane = baseLane(inferred.intents); const reasons: string[] = [`Base routing derived from ${inferred.intents.join(" + ")}.`];
  const lower = input.rawText.toLowerCase(); const imminent = Boolean(inferred.imminent) || /quarantine|notify the brand|pull the product|need an answer today|monday morning|retailer needs/.test(lower);
  if (!contact || !account) { lane = "escalate"; reasons.unshift("Force-escalated: sender could not be resolved to a verified contact; no account data was retrieved."); }
  if (!input.injected && contact && !crmSnapshot) { lane = "escalate"; reasons.unshift("Force-escalated: no fresh verified HubSpot context snapshot exists for this Slack sender."); }
  if (inferred.confidence < .65) { lane = "escalate"; reasons.unshift("Force-escalated: classifier confidence is below the safe review threshold."); }
  if (imminent) { lane = "escalate"; reasons.unshift("Force-escalated: customer signalled an imminent product, inventory, or customer action."); }
  if (inferred.intents.includes("LABEL_CLAIM_VARIANCE")) { lane = "escalate"; reasons.unshift("Force-escalated: label claim or serving-size variance requires an accountable human decision."); }
  const evidence = standardEvidence(inferred, account?.name); const placeholder = evidence.some(item => !item.citable); if (placeholder) { lane = "escalate"; reasons.unshift("Force-escalated: evidence includes a placeholder regulatory limit that is not citable."); }
  const replyGate = verifiedReplyGate({ contact, account, lane, evidence, injected: Boolean(input.injected), classification: inferred });
  if (replyGate.status === "ineligible") reasons.push(...replyGate.reasons.map(reason => `Verified-reply gate closed: ${reason}`));
  const text = compose(lane, inferred.intents, account?.name); const id = `int_${nanoid(16)}`; const row = { id, source: input.source, channelRef: input.channelRef, contactId: contact?.id ?? null, accountId: account?.id ?? null, ownerId: account?.ownerId ?? null, receivedAt: NOW(), rawText: input.rawText, intents: inferred.intents, confidence: String(inferred.confidence), imminentAction: imminent ? 1 : 0, classifierMethod: input.injected ? "fixture" : inferred.intents[0] === "UNKNOWN" ? "failsafe" : "gpt-5-mini", baseLane: baseLane(inferred.intents), lane, laneReasons: reasons, verifiedReplyStatus: replyGate.status, replyGateReasons: replyGate.reasons, acknowledgment: text.acknowledgment, draft: text.draft, evidence, precedent: inferred.intents.includes("OOS_RESULT") ? { answer: "Confirm run QC, stated method uncertainty, sample handling, and matching specification basis before asserting whether a result is a lab issue.", author: "Dr. Elena Vasquez", approvedBy: "Vijay Manohar" } : null, sendAllowed: replyGate.status === "eligible" ? 1 : 0, sendDisabled: placeholder ? 1 : 0, status: replyGate.status === "eligible" ? "auto_resolved" as const : "open" as const, msToAck: Date.now() - started, humanMinutesSaved: replyGate.status === "eligible" ? "6" : lane === "assisted" ? "4" : "0", queuePriority: severity[lane], slaMinutes: lane === "escalate" ? 15 : lane === "assisted" ? 30 : 60, resolvedAt: null, resolvedBy: null };
  await db.insert(interactions).values(row); return { duplicate: false, interaction: row };
}

export async function runFixture(fixtureId: number) { const fixture = APPENDIX_A.find(item => item.id === fixtureId); if (!fixture) throw new Error("Fixture not found"); const contact = await contactFor(fixture.contactId); return runTriage({ source: fixture.source, channelRef: `fixture|${fixture.id}|${Date.now()}`, rawText: fixture.text, slackUserId: contact?.slackUserId, slackWorkspaceId: contact?.slackWorkspaceId, injected: fixture.classification }); }
async function contactFor(id: string) { const db = await getDb(); if (!db) return undefined; return (await db.select().from(contacts).where(eq(contacts.id, id)).limit(1))[0]; }

export async function getQueue(viewerId: string, lane?: Lane) { await seed(); const db = await getDb(); if (!db) return []; const clauses = [eq(interactions.ownerId, viewerId)]; if (lane) clauses.push(eq(interactions.lane, lane)); const rows = await db.select({ interaction: interactions, account: accounts, contact: contacts }).from(interactions).leftJoin(accounts, eq(interactions.accountId, accounts.id)).leftJoin(contacts, eq(interactions.contactId, contacts.id)).where(and(...clauses)).orderBy(asc(interactions.queuePriority), desc(accounts.annualSpend), asc(interactions.receivedAt)); return rows.map(({ interaction, account, contact }) => ({ ...interaction, accountName: account?.name ?? "Unidentified sender", contactName: contact?.name ?? "Unverified sender", accountTier: account ? tier(account.annualSpend) : "—", accountType: account?.accountType ?? null })); }
export async function getItemForViewer(id: string, viewerId: string) { const db = await getDb(); if (!db) return undefined; const row = await db.select({ interaction: interactions, account: accounts, contact: contacts }).from(interactions).leftJoin(accounts, eq(interactions.accountId, accounts.id)).leftJoin(contacts, eq(interactions.contactId, contacts.id)).where(and(eq(interactions.id, id), eq(interactions.ownerId, viewerId))).limit(1); if (!row[0]) return undefined; const { interaction, account, contact } = row[0]; const productsForAccount = account ? await db.select().from(products).where(eq(products.accountId, account.id)) : []; const openOrders = account ? await db.select().from(orders).where(and(eq(orders.accountId, account.id), sql`${orders.status} <> 'released'`)) : []; const openCount = account ? await db.select({ c: sql<number>`count(*)` }).from(interactions).where(and(eq(interactions.accountId, account.id), inArray(interactions.status, ["open", "awaiting_customer"]))) : [{ c: 0 }]; const hubspotSnapshot = contact?.id ? (await db.select().from(hubspotContextSnapshots).where(and(eq(hubspotContextSnapshots.contactId, contact.id), eq(hubspotContextSnapshots.status, "available"), gte(hubspotContextSnapshots.retrievedAt, new Date(Date.now() - 15 * 60 * 1000)))).orderBy(desc(hubspotContextSnapshots.retrievedAt)).limit(1))[0] : undefined; return { ...interaction, accountName: account?.name ?? "Unidentified sender", contactName: contact?.name ?? "Unverified sender", accountTier: account ? tier(account.annualSpend) : "—", hubspotContext: hubspotSnapshot ? { source: "HubSpot MCP · read-only verified snapshot", retrievedAt: hubspotSnapshot.retrievedAt, sourceObjectIds: hubspotSnapshot.sourceObjectIds, data: hubspotSnapshot.context } : null, posture: { openOrders: openOrders.length, overdueOrders: openOrders.filter(o => o.promisedAt && o.promisedAt.getTime() < Date.now()).length, openInteractions: Number(openCount[0]?.c ?? 0), platformAccess: contact?.hasPlatformLogin ? "Active" : "No login — deflection opportunity", products: productsForAccount.map(product => product.name) } }; }
export async function recordSend(input: { interactionId: string; viewerId: string; sentText: string; overrideReason?: string; reviewed?: boolean }) { const row = await getItemForViewer(input.interactionId, input.viewerId); if (!row) throw new Error("Interaction not found in this AE queue."); if (row.sendDisabled) throw new Error("Send action disabled: a placeholder regulatory limit is present in the evidence."); if (row.lane === "assisted" && !input.reviewed) throw new Error("Assisted-lane responses require AE review before recording."); if (row.lane === "escalate" && !input.overrideReason?.trim()) throw new Error("An override reason is required for an escalate-lane item."); const db = await getDb(); if (!db) throw new Error("Database unavailable"); const original = row.draft ?? ""; const ratio = Math.min(1, Math.abs(original.length - input.sentText.length) / Math.max(original.length, input.sentText.length, 1)); await db.insert(responseFeedback).values({ id: `fb_${nanoid(14)}`, interactionId: row.id, userId: input.viewerId, draftedText: original, sentText: input.sentText, editRatio: String(ratio), category: row.intents?.[0] ?? "UNKNOWN", lane: row.lane, overrideReason: input.overrideReason?.trim() || null, createdAt: NOW() }); await db.update(interactions).set({ status: "resolved", resolvedAt: NOW(), resolvedBy: input.viewerId }).where(and(eq(interactions.id, row.id), eq(interactions.ownerId, input.viewerId))); return { editRatio: ratio }; }
export async function requestClarification(interactionId: string, viewerId: string, question: string) { const row = await getItemForViewer(interactionId, viewerId); if (!row) throw new Error("Interaction not found in this AE queue."); if (row.lane === "escalate") throw new Error("Clarification is unavailable on escalated items; a human decision is required."); if (!question.trim()) throw new Error("A specific clarification question is required."); const db = await getDb(); if (!db) throw new Error("Database unavailable"); await db.insert(clarifications).values({ id: `clar_${nanoid(14)}`, interactionId, question: question.trim(), askedAt: NOW(), answeredAt: null }); await db.update(interactions).set({ status: "awaiting_customer" }).where(and(eq(interactions.id, interactionId), eq(interactions.ownerId, viewerId))); }
export async function resolveItem(interactionId: string, viewerId: string) { const db = await getDb(); if (!db) throw new Error("Database unavailable"); await db.update(interactions).set({ status: "resolved", resolvedAt: NOW(), resolvedBy: viewerId }).where(and(eq(interactions.id, interactionId), eq(interactions.ownerId, viewerId))); }
export async function capacity() { await seed(); const db = await getDb(); if (!db) throw new Error("Database unavailable"); const rows = await db.select({ lane: interactions.lane, count: sql<number>`count(*)`, saved: sql<number>`avg(${interactions.humanMinutesSaved})` }).from(interactions).groupBy(interactions.lane); const total = rows.reduce((sum, r) => sum + Number(r.count), 0); const mix = { auto: 0, assisted: 0, escalate: 0 }; rows.forEach(r => { mix[r.lane] = total ? Number(r.count) / total : 0; }); const before = total ? rows.reduce((sum, r) => sum + Number(r.count) * Number(r.saved ?? 0), 0) / total : 0; const after = mix.assisted * 2 + mix.escalate * 6; const feedback = await db.select({ category: responseFeedback.category, ratio: sql<number>`avg(${responseFeedback.editRatio})`, count: sql<number>`count(*)` }).from(responseFeedback).groupBy(responseFeedback.category); return { total, mix, before, after, triageMultiple: after ? before / after : 0, assumptionLabel: "Assumption-based until shadow mode is active", feedback: feedback.map(item => ({ category: item.category, ratio: Number(item.ratio), count: Number(item.count) })) }; }
